/**
 * HASH-PINNED ORACLE for F-15 — the Grade All countdown's fill.
 *
 * ⚠️ DO NOT EDIT THIS FILE TO MAKE IT PASS. It is the specification; the fix
 * goes in ListenPreviewModal.svelte. If you believe an assertion here is wrong,
 * STOP and report it — do not reconcile it.
 *
 * Reported by the user from a real phone, 2026-08-05:
 *   "I expected the countdown on the button to gradually fill Grade All left to
 *    right, not gradually decrease right to left. Also when I stop it, the fill
 *    stays; it should go away."
 *
 * Two defects, one `$derived`:
 *
 *   F-15a  the fill is driven by REMAINING time, so it starts at 100% and
 *          shrinks — visually receding right→left. It must be driven by
 *          ELAPSED time: start at 0% and grow left→right.
 *
 *   F-15b  `pctRemaining` derives only from `countdown`/`countdownTotal`, and
 *          `cancelCountdown` resets neither, so on cancel the fill freezes at
 *          whatever width it had reached and stays there forever. A cancelled
 *          countdown must show NO fill.
 *
 * ⚠️ F-7 CONSTRAINT — the reason this oracle asserts on `style.width` and never
 * on presence. `ef74a33` fixed F-7 by making the button's box invariant: the
 * tick stays mounted (box held open by min-width) and the fill is absolutely
 * positioned. Do NOT fix F-15b by `{#if}`-ing the fill out of the DOM — that
 * reintroduces the exact F-7 defect class (an unmount between pointerdown and
 * pointerup eats the click). The fill element must remain in the DOM at all
 * times; only its width may change. `expectFillPresent` pins that.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, fireEvent } from "@testing-library/svelte";
import ListenPreviewModal from "./ListenPreviewModal.svelte";
import { api } from "$lib/api";
import { listenCountdownPref } from "$lib/stores/listenCountdownPref.svelte";

vi.mock("$lib/api", () => ({
  api: {
    getListenPreview: vi.fn(),
    markAsListened: vi.fn(),
    getListens: vi.fn(),
  },
}));

vi.mock("$lib/stores/listened.svelte", async () => {
  const actual = await vi.importActual<typeof import("$lib/stores/listened.svelte")>(
    "$lib/stores/listened.svelte",
  );
  return { listenedStore: actual.listenedStore };
});

const mockGetListenPreview = vi.mocked(api.getListenPreview);
const mockMarkAsListened = vi.mocked(api.markAsListened);

const createCandidate = (text: string) => ({
  kind: "create" as const,
  text,
  item_id: null,
  grade_class: "create" as const,
  rating: "good" as const,
  translation: "",
  progress: null,
  well_known: false,
  due_at: null,
  will_create: true,
});

const gradeBtn = (container: HTMLElement, key: string, grade: string) =>
  container.querySelector(
    `button[data-candidate='${key}'][data-grade='${grade}']`,
  ) as HTMLButtonElement;

/**
 * The fill's width as a number of percent.
 *
 * Asserts presence separately so an unmounted fill fails as "F-7 regression"
 * rather than silently reading as 0 and passing F-15b for the wrong reason.
 * That distinction is the whole point: 0% and "not in the DOM" look identical
 * to a naive reader and are opposite outcomes here.
 */
function fillPct(container: HTMLElement): number {
  const fill = container.querySelector<HTMLElement>(".grade-all .fill");
  expect(
    fill,
    "F-7 REGRESSION: the .fill element must stay mounted at all times — the button's box must not change",
  ).not.toBeNull();
  const raw = fill!.style.width;
  expect(raw, "the fill must carry an explicit percentage width").toMatch(/^-?[\d.]+%$/);
  return parseFloat(raw);
}

beforeEach(() => {
  vi.clearAllMocks();
  vi.useRealTimers();
  listenCountdownPref.set("10");
});

afterEach(() => {
  vi.useRealTimers();
});

describe("F-15 — the Grade All countdown fill", () => {
  it("F-15a: fills left→right — 0% at the start, growing as time elapses", async () => {
    vi.useFakeTimers();
    mockGetListenPreview.mockResolvedValue({ candidates: [createCandidate("kava")] });
    mockMarkAsListened.mockResolvedValue({
      status: "ok",
      created: 1,
      staged: 0,
      applied: 0,
      remaining_candidates: 0,
      listen_count: 1,
    });

    const { container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await vi.advanceTimersByTimeAsync(0);

    // Sanity: the countdown really is armed. Without this the width assertions
    // below could pass against a countdown that never started (0% forever),
    // which is the vacuity trap this whole finding came out of.
    expect(container.querySelector(".grade-all")?.getAttribute("data-countdown")).toBe("running");

    // t=0, 10 of 10 seconds remain → NOTHING has elapsed → empty.
    // The pre-fix code yields 100 here. This is the assertion that discriminates
    // direction; the midpoint (t=5s) reads 50 either way and proves nothing.
    expect(fillPct(container)).toBe(0);

    // t=8s, 2 of 10 remain → 80% elapsed. Pre-fix: 20.
    await vi.advanceTimersByTimeAsync(8_000);
    expect(fillPct(container)).toBe(80);
  });

  it("F-15b: cancelling clears the fill (and never unmounts it)", async () => {
    vi.useFakeTimers();
    mockGetListenPreview.mockResolvedValue({ candidates: [createCandidate("kava")] });
    mockMarkAsListened.mockResolvedValue({
      status: "ok",
      created: 1,
      staged: 0,
      applied: 0,
      remaining_candidates: 0,
      listen_count: 1,
    });

    const { container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await vi.advanceTimersByTimeAsync(0);

    // Let it run far enough that a frozen fill is unmistakably non-zero.
    await vi.advanceTimersByTimeAsync(6_000);
    expect(fillPct(container)).toBeGreaterThan(0);

    // Cancel by grading a row — the same cancellation path F-7 covers.
    await fireEvent.click(gradeBtn(container, "create:kava", "hard"));

    expect(container.querySelector(".grade-all")?.getAttribute("data-countdown")).toBe("idle");
    // The fill must be gone visually but present structurally.
    expect(fillPct(container)).toBe(0);

    // And it must stay gone — no late tick may repaint it.
    await vi.advanceTimersByTimeAsync(15_000);
    expect(fillPct(container)).toBe(0);
    expect(mockMarkAsListened).not.toHaveBeenCalled();
  });

  it("F-15b: a countdown that never started shows no fill", async () => {
    // pref 'off' → countdownTotal stays 0. Guards the divide-by-zero branch and
    // pins that "not running" and "just started" agree on 0% — so F-15a's
    // start-state assertion cannot be satisfied by accidentally disarming.
    listenCountdownPref.set("off");
    mockGetListenPreview.mockResolvedValue({ candidates: [createCandidate("kava")] });

    const { container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await vi.waitFor(() => {
      expect(container.querySelector(".grade-all")).not.toBeNull();
    });

    expect(container.querySelector(".grade-all")?.getAttribute("data-countdown")).toBe("idle");
    expect(fillPct(container)).toBe(0);
  });
});
