/**
 * Orchestrator-authored contract for opting a row PAST the daily new-card cap.
 * Brief: docs/briefs/bp-listen-over-cap-optin-2026-08.md (Stage 2, §5).
 *
 * ⚠️ DO NOT EDIT THIS FILE while implementing. It is authored ahead of the
 * implementation on purpose: this is NEW semantics, and an executor who writes
 * both the behaviour and its test can only prove the two agree with each other.
 * If an assertion here looks wrong, STOP and report it — do not adjust it to
 * match what you built.
 *
 * The change in one sentence: an over-budget ("tail") row used to render
 * read-only; it now renders its grade control with NO rating pre-set, so that
 * explicitly grading one row — and only that row — carries it past the daily
 * new-card cap.
 *
 * Why this is not a parity bug: it is exactly Anki's Custom Study → "Increase
 * today's new card limit", a user-initiated limit increase. It is self-limiting
 * by construction — the overage feeds `count_new_created_today` /
 * `count_new_introduced_today`, which drive the next listen's budget toward 0.
 * There is no persisted override flag and no overage counter; do not add one.
 *
 * Companion files:
 *  - `backend/tests/test_api_listen_over_cap_optin.py` — the backend oracle.
 *  - `ListenPreviewModal.creationTail.test.ts` — the partition invariant
 *    (nothing is ever promoted across the divider), still pinned there.
 *
 * ── The two rules that carry the risk ──────────────────────────────────
 *
 * 1. `Grade All` / `Skip All` must NOT touch tail rows. A bulk action that
 *    silently blows through the daily cap is the entire risk of this feature.
 *    Exceeding the cap has to cost one deliberate tap per row.
 * 2. An UNTOUCHED tail row still emits NOTHING. The polarity is inverted for
 *    create rows — absent from `word_ratings` means the backend's default
 *    "good", which CREATES the card — so silence is the only safe default, and
 *    it matters more now, not less, since the row finally has a control.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, fireEvent, waitFor } from "@testing-library/svelte";
import ListenPreviewModal from "./ListenPreviewModal.svelte";
import { api, type ListenPreviewCandidate } from "$lib/api";
import { listenCountdownPref } from "$lib/stores/listenCountdownPref.svelte";

vi.mock("$lib/api", () => ({
  api: {
    getListenPreview: vi.fn(),
    markAsListened: vi.fn(),
    getListens: vi.fn(),
  },
}));

vi.mock("$lib/stores/listened.svelte", async () => {
  const actual = await vi.importActual<typeof import("$lib/stores/listened.svelte")>(
    "$lib/stores/listened.svelte",
  );
  return { listenedStore: actual.listenedStore };
});

const mockGetListenPreview = vi.mocked(api.getListenPreview);
const mockMarkAsListened = vi.mocked(api.markAsListened);

beforeEach(() => {
  vi.clearAllMocks();
  vi.useRealTimers();
  listenCountdownPref.set("off");
});

// ── Fixtures ──────────────────────────────────────────────────────────

const createCandidate = (text: string, willCreate: boolean): ListenPreviewCandidate => ({
  kind: "create" as const,
  text,
  item_id: null,
  grade_class: "create" as const,
  rating: "good" as const,
  translation: "",
  progress: null,
  well_known: false,
  due_at: null,
  will_create: willCreate,
});

/** A carded-but-never-introduced word — the population that really does spend
 *  Anki's daily new allowance when its staged grade is released. */
const newStateCandidate = (text: string, willCreate: boolean): ListenPreviewCandidate => ({
  kind: "word" as const,
  text,
  item_id: 42,
  grade_class: "new" as const,
  rating: "good" as const,
  translation: "",
  progress: null,
  well_known: false,
  due_at: null,
  will_create: willCreate,
});

const kpCandidate = (text: string, willCreate: boolean): ListenPreviewCandidate => ({
  kind: "kp" as const,
  text,
  item_id: 99,
  grade_class: "new" as const,
  rating: "good" as const,
  translation: "",
  progress: null,
  well_known: false,
  due_at: null,
  will_create: willCreate,
});

/** Budget = 2, tail = 3 — the same shape the creationTail oracle uses. */
const previewWithTail = () => ({
  candidates: [
    createCandidate("kake", true),
    createCandidate("melk", true),
    createCandidate("brød", false),
    createCandidate("smør", false),
    createCandidate("ost", false),
  ],
});

const listenResult = {
  status: "ok",
  created: 0,
  staged: 0,
  applied: 0,
  remaining_candidates: 0,
  listen_count: 1,
};

const gradeBtn = (container: HTMLElement, key: string, grade: string) =>
  container.querySelector(
    `button[data-candidate='${key}'][data-grade='${grade}']`,
  ) as HTMLButtonElement | null;

const allGradeBtns = (container: HTMLElement, key: string) =>
  [...container.querySelectorAll(`button[data-candidate='${key}']`)] as HTMLButtonElement[];

const rowFor = (container: HTMLElement, text: string) =>
  [...container.querySelectorAll("li.candidate")].find(
    (li) => li.querySelector(".text")?.textContent === text,
  );

// ── Tests ─────────────────────────────────────────────────────────────

describe("ListenPreviewModal — opting past the daily new-card cap", () => {
  it("gives a tail row a grade control with NO rating pre-set", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    // The tail row is gradeable — that control IS the opt-in affordance.
    const tailBtns = allGradeBtns(container, "create:brød");
    expect(tailBtns.length).toBeGreaterThan(0);

    // …but nothing is pre-decided. Every button, Skip included, is unpressed.
    // A pre-set "good" would create the card the user never asked for; a
    // pre-set "skip" would assert a refusal they never made.
    for (const b of tailBtns) {
      expect(b.getAttribute("aria-pressed")).toBe("false");
    }

    // A LIVE row is unchanged: it still defaults to good.
    expect(gradeBtn(container, "create:kake", "good")!.getAttribute("aria-pressed")).toBe("true");
  });

  it("sends the rating AND the text in over_cap_words when a tail row is graded", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(gradeBtn(container, "create:brød", "good")!);

    await waitFor(() => getByText("Mark 3 as listened"));
    await fireEvent.click(getByText("Mark 3 as listened"));

    await waitFor(() => {
      // Both halves are required. The rating alone is not enough: absent from
      // over_cap_words the backend leaves the row past the budget and creates
      // nothing. The name alone is not enough either — that is what tells the
      // backend this specific row was a deliberate choice.
      expect(mockMarkAsListened).toHaveBeenCalledWith(
        "l1",
        { brød: "good" },
        {},
        [],
        [],
        ["brød"],
        [],
      );
    });
  });

  it("routes an opted-in key phrase to over_cap_kps, not over_cap_words", async () => {
    // The two lists are not interchangeable — the backend honours a key phrase
    // ONLY from over_cap_kps, mirroring the confirmed_words/confirmed_kps split.
    mockGetListenPreview.mockResolvedValue({
      candidates: [kpCandidate("dober dan", true), kpCandidate("lahko noc", false)],
    });
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("dober dan"));
    await fireEvent.click(gradeBtn(container, "kp:lahko noc", "hard")!);

    await waitFor(() => getByText("Mark 2 as listened"));
    await fireEvent.click(getByText("Mark 2 as listened"));

    await waitFor(() => {
      expect(mockMarkAsListened).toHaveBeenCalledWith(
        "l1",
        {},
        { "lahko noc": "hard" },
        [],
        [],
        [],
        ["lahko noc"],
      );
    });
  });

  it("opts in an over-budget NEW-state row through over_cap_words", async () => {
    // This is the population that actually spends the allowance: releasing its
    // staged grade stamps `introduced_at`. It still rides over_cap_words,
    // because it is a word row.
    mockGetListenPreview.mockResolvedValue({
      candidates: [newStateCandidate("hansen", true), newStateCandidate("lund", false)],
    });
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("hansen"));
    await fireEvent.click(gradeBtn(container, "word:lund", "easy")!);

    await waitFor(() => getByText("Mark 2 as listened"));
    await fireEvent.click(getByText("Mark 2 as listened"));

    await waitFor(() => {
      expect(mockMarkAsListened).toHaveBeenCalledWith(
        "l1",
        { lund: "easy" },
        {},
        [],
        [],
        ["lund"],
        [],
      );
    });
  });

  it("still sends NOTHING for an untouched tail row", async () => {
    // The polarity invariant, restated for the world where the row has a
    // control. Absent ⇒ the backend defaults to "good" ⇒ it CREATES the card,
    // so an untouched tail row must contribute nothing to any of the four maps.
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("Mark 2 as listened"));
    await fireEvent.click(getByText("Mark 2 as listened"));

    await waitFor(() => {
      expect(mockMarkAsListened).toHaveBeenCalledWith("l1", {}, {}, [], [], [], []);
    });
  });

  it("treats Skip on a tail row as UN-opting, not as a decision", async () => {
    // A tail row is already "not happening", so a skip on one asserts nothing
    // new — it is the undo for a mis-tapped opt-in, and the only way back to
    // unset once a rating exists. It must therefore emit nothing at all, the
    // same as never having touched the row. (The backend agrees independently:
    // test_api_listen_creation_skip_consumes_slot.py pins that naming a tail
    // row with "skip" is inert.)
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    await fireEvent.click(gradeBtn(container, "create:brød", "good")!);
    await waitFor(() => getByText("Mark 3 as listened"));

    await fireEvent.click(gradeBtn(container, "create:brød", "skip")!);
    await waitFor(() => getByText("Mark 2 as listened"));

    await fireEvent.click(getByText("Mark 2 as listened"));

    await waitFor(() => {
      expect(mockMarkAsListened).toHaveBeenCalledWith("l1", {}, {}, [], [], [], []);
    });
  });

  it("lifts the dimming on an opted-in row but keeps it in the tail partition", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    expect(rowFor(container, "brød")!.classList.contains("tail")).toBe(true);
    expect(rowFor(container, "brød")!.classList.contains("opted")).toBe(false);

    await fireEvent.click(gradeBtn(container, "create:brød", "good")!);

    await waitFor(() => {
      // Reads as live…
      expect(rowFor(container, "brød")!.classList.contains("opted")).toBe(true);
    });
    // …but is NOT promoted. `.tail` is partition identity and must survive, or
    // the divider starts moving and we are back at promote-on-uncheck
    // (rejected 2026-07-31). `.tail.opted` is what lifts the dim.
    expect(rowFor(container, "brød")!.classList.contains("tail")).toBe(true);
    // And the row stays physically below the cut line, in place.
    const rows = [...container.querySelectorAll("li.candidate")].map(
      (li) => li.querySelector(".text")?.textContent,
    );
    expect(rows).toEqual(["kake", "melk", "brød", "smør", "ost"]);
  });

  it("states the overage out loud once a row is opted in", async () => {
    // The user is exceeding a limit on purpose; the UI says the number rather
    // than quietly moving the denominator.
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    expect(getByText("Introducing 2 of 5 today — daily new-card limit")).toBeTruthy();

    await fireEvent.click(gradeBtn(container, "create:brød", "good")!);

    await waitFor(() => {
      expect(getByText("Introducing 2 of 5 today — daily new-card limit (+1 over)")).toBeTruthy();
    });

    await fireEvent.click(gradeBtn(container, "create:ost", "good")!);

    await waitFor(() => {
      expect(getByText("Introducing 2 of 5 today — daily new-card limit (+2 over)")).toBeTruthy();
    });
  });

  it("Grade All leaves every tail row unset and sends no over_cap_words", async () => {
    // The hard requirement: a bulk action must never blow through the cap.
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(getByText("Grade All"));

    await waitFor(() => expect(getByText("Mark 2 as listened")).toBeTruthy());

    for (const text of ["brød", "smør", "ost"]) {
      for (const b of allGradeBtns(container, `create:${text}`)) {
        expect(b.getAttribute("aria-pressed")).toBe("false");
      }
      expect(rowFor(container, text)!.classList.contains("opted")).toBe(false);
    }
    expect(getByText("Introducing 2 of 5 today — daily new-card limit")).toBeTruthy();

    await fireEvent.click(getByText("Mark 2 as listened"));

    await waitFor(() => {
      expect(mockMarkAsListened).toHaveBeenCalledWith("l1", {}, {}, [], [], [], []);
    });
  });

  it("Skip All leaves every tail row unset and sends no over_cap_words", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(getByText("Skip All"));

    await waitFor(() => expect(getByText("Mark as listened")).toBeTruthy());

    for (const text of ["brød", "smør", "ost"]) {
      for (const b of allGradeBtns(container, `create:${text}`)) {
        expect(b.getAttribute("aria-pressed")).toBe("false");
      }
    }

    await fireEvent.click(getByText("Mark as listened"));

    await waitFor(() => {
      // Only the two LIVE rows are named. No tail row appears anywhere.
      expect(mockMarkAsListened).toHaveBeenCalledWith(
        "l1",
        { kake: "skip", melk: "skip" },
        {},
        [],
        [],
        [],
        [],
      );
    });
  });

  it("counts opt-ins in the footer, so the button tells the truth", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => expect(getByText("Mark 2 as listened")).toBeTruthy());

    await fireEvent.click(gradeBtn(container, "create:brød", "good")!);
    await waitFor(() => expect(getByText("Mark 3 as listened")).toBeTruthy());

    await fireEvent.click(gradeBtn(container, "create:ost", "hard")!);
    await waitFor(() => expect(getByText("Mark 4 as listened")).toBeTruthy());
  });

  it("opts in a tail row ranked LAST, several rows past the cut", async () => {
    // Frontend mirror of the backend's break→continue regression test: the
    // bottom row of the tail must be just as reachable as the top one.
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(gradeBtn(container, "create:ost", "good")!);

    await waitFor(() => getByText("Mark 3 as listened"));
    await fireEvent.click(getByText("Mark 3 as listened"));

    await waitFor(() => {
      expect(mockMarkAsListened).toHaveBeenCalledWith(
        "l1",
        { ost: "good" },
        {},
        [],
        [],
        ["ost"],
        [],
      );
    });
  });
});
