/**
 * Orchestrator-authored contract for the over-budget creation tail.
 * Brief: docs/briefs/bp-listen-preview-creation-budget-ux-2026-07.md (Option B).
 *
 * ⚠️ DO NOT EDIT THIS FILE while implementing the brief. It is authored ahead of
 * the implementation on purpose: promote-on-uncheck is NEW commit semantics, and
 * an executor who writes both the behavior and its test can only prove the two
 * agree with each other. If an assertion here looks wrong, STOP and report it —
 * do not adjust it to match what you built.
 *
 * ⚠️ EXPECTED RED STATE, in this order:
 *   1. Before backend Step 1, `will_create` is not on the generated
 *      `ListenPreviewCandidate` type, so `bun run check` fails on this file.
 *      That is correct. Fix it by shipping Step 1 (add the field, then
 *      `dump_openapi.py` + `bun run gen:api`) — NOT by deleting the field from
 *      these fixtures.
 *   2. After Step 1 and before Step 2, these tests fail at runtime because the
 *      modal still renders every create row as gradeable.
 *
 * Measured red state at authoring time (2026-07-31, before any implementation):
 * `bun run check` → 1 error on the `createCandidate` return annotation; vitest →
 * 9 failed | 1 passed. The one that passes is "shows no tail disclosure when the
 * budget covers everything" — the degenerate all-live case, which the current
 * modal already satisfies. It is a regression guard, not a driver; if it ever
 * goes red, tail rendering has leaked into previews that have no tail.
 *
 * The invariant under test: the server spends the creation budget by RANK, not
 * by row identity — `_rank_listen_candidates` sorts with a STABLE sort, so
 * removing one candidate never reorders the rest. "The first N still-checked
 * create rows, in the order the server sent them" is therefore exactly what
 * `mark_lesson_listened` will create. The modal must show that, live.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, fireEvent, waitFor } from "@testing-library/svelte";
import ListenPreviewModal from "./ListenPreviewModal.svelte";
import { api, type ListenPreviewCandidate } from "$lib/api";
import { listenCountdownPref } from "$lib/stores/listenCountdownPref.svelte";

vi.mock("$lib/api", () => ({
  api: {
    getListenPreview: vi.fn(),
    markAsListened: vi.fn(),
    getListens: vi.fn(),
  },
}));

vi.mock("$lib/stores/listened.svelte", async () => {
  const actual = await vi.importActual<typeof import("$lib/stores/listened.svelte")>(
    "$lib/stores/listened.svelte",
  );
  return { listenedStore: actual.listenedStore };
});

const mockGetListenPreview = vi.mocked(api.getListenPreview);
const mockMarkAsListened = vi.mocked(api.markAsListened);

beforeEach(() => {
  vi.clearAllMocks();
  vi.useRealTimers();
  // The countdown auto-commits; every test here drives the commit itself.
  listenCountdownPref.set("off");
});

// ── Fixtures ──────────────────────────────────────────────────────────

/**
 * A create row. `will_create: false` is an over-budget (tail) row.
 *
 * The explicit `ListenPreviewCandidate` annotation is load-bearing: without it
 * TypeScript widens the returned literal and an unknown `will_create` sails
 * through structurally, so the field would not be pinned at the type level at
 * all. Annotated, this file does not compile until Step 1 adds the field.
 */
const createCandidate = (text: string, willCreate: boolean): ListenPreviewCandidate => ({
  kind: "create" as const,
  text,
  item_id: null,
  grade_class: "create" as const,
  rating: "good" as const,
  translation: "",
  progress: null,
  well_known: false,
  due_at: null,
  will_create: willCreate,
});

/**
 * The response shape Step 1 must produce: create rows first, in rank order,
 * live rows before tail rows. Budget = 2 here, tail = 3.
 */
const previewWithTail = () => ({
  candidates: [
    createCandidate("kake", true),
    createCandidate("melk", true),
    createCandidate("brød", false),
    createCandidate("smør", false),
    createCandidate("ost", false),
  ],
});

const listenResult = {
  status: "ok",
  created: 0,
  staged: 0,
  applied: 0,
  remaining_candidates: 0,
  listen_count: 1,
};

const gradeBtn = (container: HTMLElement, key: string, grade: string) =>
  container.querySelector(
    `button[data-candidate='${key}'][data-grade='${grade}']`,
  ) as HTMLButtonElement | null;

const isActive = (b: HTMLButtonElement) => b.classList.contains("active");

/** A row is LIVE iff it carries the grade control; a tail row is read-only. */
const isLive = (container: HTMLElement, text: string) =>
  container.querySelector(`button[data-candidate='create:${text}']`) !== null;

// ── Tests ─────────────────────────────────────────────────────────────

describe("ListenPreviewModal — over-budget creation tail", () => {
  it("renders the tail read-only inside its own disclosure, in server order", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    // Live rows are gradeable; tail rows are rendered but carry no control.
    expect(isLive(container, "kake")).toBe(true);
    expect(isLive(container, "melk")).toBe(true);
    expect(isLive(container, "brød")).toBe(false);
    expect(isLive(container, "smør")).toBe(false);
    expect(isLive(container, "ost")).toBe(false);

    // The tail is still visible — disclosure, not deletion. That is the
    // entire point of the feature.
    expect(getByText("brød")).toBeTruthy();
    expect(getByText("ost")).toBeTruthy();
    expect(getByText("3 more — next listen")).toBeTruthy();

    // Server order is preserved in the DOM: brød before smør before ost.
    const body = container.textContent ?? "";
    expect(body.indexOf("brød")).toBeLessThan(body.indexOf("smør"));
    expect(body.indexOf("smør")).toBeLessThan(body.indexOf("ost"));
  });

  it("unchecking a live create promotes exactly one tail row, the first in order", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    await fireEvent.click(gradeBtn(container, "create:kake", "skip")!);

    await waitFor(() => {
      // The freed slot goes to the FIRST tail row, matching the server's
      // stable re-rank — not to an arbitrary one.
      expect(isLive(container, "brød")).toBe(true);
    });

    // Exactly one promotion: the rest of the tail stays read-only.
    expect(isLive(container, "smør")).toBe(false);
    expect(isLive(container, "ost")).toBe(false);
    expect(getByText("2 more — next listen")).toBeTruthy();

    // The promoted row is a normal live row: default "good", gradeable.
    expect(isActive(gradeBtn(container, "create:brød", "good")!)).toBe(true);

    // The skipped row stays visible and stays skipped — it does not vanish
    // into the tail (the user's choice must remain legible and reversible).
    expect(isLive(container, "kake")).toBe(true);
    expect(isActive(gradeBtn(container, "create:kake", "skip")!)).toBe(true);
  });

  it("re-checking the skipped row demotes the promoted one back into the tail", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    await fireEvent.click(gradeBtn(container, "create:kake", "skip")!);
    await waitFor(() => expect(isLive(container, "brød")).toBe(true));

    await fireEvent.click(gradeBtn(container, "create:kake", "good")!);

    await waitFor(() => {
      expect(isLive(container, "brød")).toBe(false);
    });
    expect(getByText("3 more — next listen")).toBeTruthy();
  });

  it("keeps the footer count at what the listen will actually create", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    // Budget 2, both live rows on "good" — the tail contributes nothing.
    await waitFor(() => expect(getByText("Mark 2 as listened")).toBeTruthy());

    // Unchecking one promotes one, so the listen still creates 2. The count
    // must reflect the promotion, not the uncheck.
    await fireEvent.click(gradeBtn(container, "create:kake", "skip")!);

    await waitFor(() => expect(getByText("Mark 2 as listened")).toBeTruthy());
  });

  it("sends nothing for tail rows — not 'skip', not 'good'", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("Mark 2 as listened"));
    await fireEvent.click(getByText("Mark 2 as listened"));

    await waitFor(() => {
      // Both live rows are default-good, so they are omitted too: an empty
      // word_ratings map is the correct payload for an untouched preview.
      //
      // ⚠️ Polarity trap, opposite to the well-known rows a few lines up in
      // the component: absent ⇒ the backend defaults to "good" and CREATES the
      // card (budget permitting). Emitting "skip" for a tail row would drop it
      // from lemma_candidates server-side and suppress the very promotion this
      // feature exists to display.
      expect(mockMarkAsListened).toHaveBeenCalledWith("l1", {}, {}, [], []);
    });
  });

  it("sends 'skip' for an unchecked live row, and still nothing for the tail", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(gradeBtn(container, "create:kake", "skip")!);
    await fireEvent.click(getByText("Mark 2 as listened"));

    await waitFor(() => {
      // "kake" is skipped; brød is promoted but default-good, so it is omitted
      // and the server re-ranks onto it by itself. The client names no create.
      expect(mockMarkAsListened).toHaveBeenCalledWith("l1", { kake: "skip" }, {}, [], []);
    });
  });

  it("Skip All skips the live rows without dragging the tail into the payload", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(getByText("Skip All"));
    await fireEvent.click(getByText("Mark as listened"));

    await waitFor(() => {
      // Only rows that were live when Skip All ran are named. Tail rows are not
      // in the ratings map at all — skipAll must iterate the live set, not
      // `candidates`.
      //
      // NOTE (surfaced, not introduced, by this feature): naming kake+melk as
      // skipped frees both slots server-side, so the commit creates brød+smør
      // instead. That is today's behavior made visible. If it should instead
      // consume the slot, that is a SERVER change and a separate decision —
      // do not "fix" it here.
      expect(mockMarkAsListened).toHaveBeenCalledWith(
        "l1",
        { kake: "skip", melk: "skip" },
        {},
        [],
        [],
      );
    });
  });

  it("Grade All does not pull tail rows above the divider", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(getByText("Grade All"));

    await waitFor(() => expect(getByText("Mark 2 as listened")).toBeTruthy());
    expect(isLive(container, "brød")).toBe(false);
    expect(getByText("3 more — next listen")).toBeTruthy();
  });

  it("a zero budget puts every create in the tail and grades none", async () => {
    // A same-day re-listen: new_cap already spent, creation_budget == 0.
    mockGetListenPreview.mockResolvedValue({
      candidates: [createCandidate("brød", false), createCandidate("smør", false)],
    });

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("brød"));

    expect(isLive(container, "brød")).toBe(false);
    expect(isLive(container, "smør")).toBe(false);
    expect(getByText("2 more — next listen")).toBeTruthy();
    expect(getByText("Mark as listened")).toBeTruthy();
  });

  it("shows no tail disclosure when the budget covers everything", async () => {
    mockGetListenPreview.mockResolvedValue({
      candidates: [createCandidate("kake", true), createCandidate("melk", true)],
    });

    const { getByText, queryByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    expect(isLive(container, "kake")).toBe(true);
    expect(isLive(container, "melk")).toBe(true);
    expect(queryByText(/more — next listen/)).toBeNull();
  });
});
