/**
 * HASH-PINNED ORACLE for F-20 (+ F-16's DOM contract).
 * Brief: bd tunatale-g54 (closed)
 *
 * ⚠️ DO NOT EDIT THIS FILE while implementing. It is authored ahead of the
 * implementation on purpose: this is NEW presentation semantics, and an executor
 * who writes both the behaviour and its test can only prove the two agree with
 * each other. If an assertion here looks wrong, STOP and report it — do not
 * adjust it to match what you built.
 *
 * ── What is being fixed ───────────────────────────────────────────────
 *
 * `cutLineText` renders as `<li class="cut-line">`, the LAST child of the list.
 * With 167 live rows the sentence explaining the cut renders after every row it
 * explains — you can only read it by scrolling past the entire list, while the
 * tail disclosure (its consequence) sits above the fold. The two also restate
 * each other: "Introducing 8 of 12 today" and "4 words for subsequent listens"
 * are the same fact twice, since 12 - 8 = 4.
 *
 * It is drift, not a bad original decision: the cut line used to sit at a real
 * visual boundary with the over-budget rows inline beneath it. F-13 moved the
 * tail into a disclosure and the line stayed where the boundary used to be.
 *
 * ── The replacement (user's choice: option C, 2026-08-05) ─────────────
 *
 * A three-count summary ABOVE the list: what happens now, what waits, what is
 * hidden as known. This is the only option in which the known group joins the
 * picture — it is a third partition that nothing currently summarises.
 *
 * ── The wording, and why it is not "next time" ────────────────────────
 *
 * User: "not all the words may show up exactly next time; it may take multiple
 * listens." Correct, and the scheduler proves it: `_allocate_new_state_budget`
 * prices NEW-state rows first and hands creation `max(0, budget - charged)`, so
 * a lesson whose NEW backlog is at or above the cap yields a creation budget of
 * ZERO for as many listens as that holds — measured across two separate days.
 * `later` promises no schedule. That is the whole point of the word.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, fireEvent, waitFor } from "@testing-library/svelte";
import ListenPreviewModal from "./ListenPreviewModal.svelte";
import { api, type ListenPreviewCandidate } from "$lib/api";
import { listenCountdownPref } from "$lib/stores/listenCountdownPref.svelte";

vi.mock("$lib/api", () => ({
  api: {
    getListenPreview: vi.fn(),
    markAsListened: vi.fn(),
    getListens: vi.fn(),
  },
}));

vi.mock("$lib/stores/listened.svelte", async () => {
  const actual = await vi.importActual<typeof import("$lib/stores/listened.svelte")>(
    "$lib/stores/listened.svelte",
  );
  return { listenedStore: actual.listenedStore };
});

const mockGetListenPreview = vi.mocked(api.getListenPreview);

beforeEach(() => {
  vi.clearAllMocks();
  vi.useRealTimers();
  listenCountdownPref.set("off");
});

// ── Fixtures ──────────────────────────────────────────────────────────

const base = {
  item_id: 42,
  rating: "good" as const,
  translation: "",
  progress: 0.3,
  well_known: false,
  due_at: null,
  will_create: true,
};

const liveCreate = (text: string): ListenPreviewCandidate => ({
  ...base,
  kind: "create",
  text,
  grade_class: "create",
  item_id: null,
});
const tailCreate = (text: string): ListenPreviewCandidate => ({
  ...base,
  kind: "create",
  text,
  grade_class: "create",
  item_id: null,
  will_create: false,
});
const liveNewState = (text: string): ListenPreviewCandidate => ({
  ...base,
  kind: "word",
  text,
  grade_class: "new",
});
const dueRow = (text: string): ListenPreviewCandidate => ({
  ...base,
  kind: "word",
  text,
  grade_class: "due",
  due_at: "2026-08-04T04:00:00+00:00",
});
const knownRow = (text: string): ListenPreviewCandidate => ({
  ...base,
  kind: "word",
  text,
  grade_class: "ahead",
  well_known: true,
  progress: 0.95,
  due_at: "2126-01-01T04:00:00+00:00",
});

/**
 * Deliberately asymmetric so a transposed pair of counts cannot pass:
 *   now = 5   (2 live creates + 1 live NEW-state + 2 ordinary due rows)
 *   later = 2 (2 tail creates)
 *   known = 3 (3 well-known rows)
 * Revised 2026-08-09 (user request): `now` counts every row that will
 * actually be graded/created when this listen is committed — liveCandidates,
 * not just the introduction-budget subset. The 2 ordinary due rows now DO
 * belong to `now`; only well-known rows (excluded from grading by default)
 * and the un-opted tail (explicitly not happening now) stay out of it. 5 + 2
 * + 3 sums to the fixture's 10 rows exactly.
 */
const preview = () => ({
  candidates: [
    liveCreate("alle"),
    liveCreate("én"),
    liveNewState("innover"),
    tailCreate("smelte"),
    tailCreate("notatboka"),
    dueRow("helst"),
    dueRow("nabolag"),
    knownRow("hvala"),
    knownRow("takk"),
    knownRow("bergen"),
  ],
});

// ── Helpers ───────────────────────────────────────────────────────────

/** The summary's segments, as [number, label] pairs in render order. Reads the
 *  rendered TEXT rather than any class name, so the markup stays free. */
const segments = (container: HTMLElement): [string, string][] => {
  const row = container.querySelector(".partition");
  if (!row) return [];
  return [...row.querySelectorAll(":scope > *")].map((seg) => {
    const n = seg.querySelector(".n")?.textContent?.trim() ?? "";
    const l = seg.querySelector(".l")?.textContent?.trim() ?? "";
    return [n, l];
  });
};

const gradeBtn = (container: HTMLElement, key: string, grade: string) =>
  container.querySelector(
    `button[data-candidate='${key}'][data-grade='${grade}']`,
  ) as HTMLButtonElement;

// ── Tests ─────────────────────────────────────────────────────────────

describe("F-20 — the three-count summary replaces the cut line", () => {
  it("renders now / later / known with the right numbers and the exact labels", async () => {
    mockGetListenPreview.mockResolvedValue(preview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("alle"));

    // ⚠️ The labels are PINNED VERBATIM. `321c3ca` shipped a line reading
    // `limit(+1 over)` — Svelte trims the leading whitespace of an {#if} body —
    // and only an exact-string assertion caught it. A regex or a function
    // matcher would have let it through.
    expect(segments(container)).toEqual([
      ["5", "now"],
      ["2", "later"],
      ["3", "known"],
    ]);
  });

  it("puts the summary ABOVE the list — the defect is a position, not a wording", async () => {
    mockGetListenPreview.mockResolvedValue(preview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("alle"));

    const summary = container.querySelector(".partition")!;
    const list = container.querySelector("ul.list")!;
    expect(summary).toBeTruthy();
    expect(list).toBeTruthy();
    // DOCUMENT_POSITION_FOLLOWING === 4: the list comes AFTER the summary.
    // Without this, a summary that still renders at the bottom of a 167-row
    // list would satisfy every other assertion in this file.
    expect(summary.compareDocumentPosition(list) & 4).toBeTruthy();
  });

  it("deletes the cut line entirely — its meaning now lives in the summary", async () => {
    mockGetListenPreview.mockResolvedValue(preview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("alle"));

    expect(container.querySelector(".cut-line")).toBeNull();
    expect(container.textContent).not.toContain("daily new-card limit");
    expect(container.textContent).not.toContain("Introducing");
  });

  it("leaves the tail disclosure's wording ALONE", async () => {
    // The mock that proposed this change also rewrote this string to
    // "2 words · next listen", carrying the very overstatement the user
    // rejected into a second place. The shipped wording is already correct and
    // is the user's own. It does not change.
    mockGetListenPreview.mockResolvedValue(preview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("alle"));

    const tailSummary = container.querySelector("details.tail-group summary");
    expect(tailSummary?.textContent).toBe("2 words for subsequent listens");
  });
});

describe("F-20 — the over-cap opt-in keeps its voice", () => {
  it("moves an opted row from later into now, and says so out loud", async () => {
    // `cutLineText` carried ` (+N over)` and its comment is explicit about why:
    // "they are exceeding a limit on purpose, so the UI says the number out loud
    // rather than quietly moving the denominator". Deleting the cut line must
    // not delete that. An opted row IS being introduced now, so the counts move
    // with it and the caption states the overage.
    mockGetListenPreview.mockResolvedValue(preview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("alle"));

    await fireEvent.click(gradeBtn(container, "create:smelte", "good"));

    expect(segments(container)).toEqual([
      ["6", "now"],
      ["1", "later"],
      ["3", "known"],
    ]);
    // PINNED VERBATIM, spacing included.
    expect(container.textContent).toContain("+1 past today's limit");
  });

  it("says nothing at all when nothing was opted in", async () => {
    // The common case is three segments and no prose. A caption that always
    // renders would be the cut line back, one line higher.
    mockGetListenPreview.mockResolvedValue(preview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("alle"));

    expect(container.textContent).not.toContain("past today's limit");
  });

  it("a SKIPPED tail row is not an opt-in", async () => {
    // Skip is the undo, not a decision to exceed the cap. If skipping moved the
    // counts, the summary would claim an introduction the commit never makes.
    mockGetListenPreview.mockResolvedValue(preview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("alle"));

    await fireEvent.click(gradeBtn(container, "create:smelte", "skip"));

    expect(segments(container)).toEqual([
      ["5", "now"],
      ["2", "later"],
      ["3", "known"],
    ]);
    expect(container.textContent).not.toContain("past today's limit");
  });
});

describe("F-16 — the two disclosures share one rule set", () => {
  it("gives the tail group and the known group a class in common", async () => {
    // Root cause of F-16: `.tail-group` has NO CSS AT ALL — it appears once, in
    // the markup, with no matching rule — so it renders as a default <details>
    // while its sibling carries the treatment the user wants.
    //
    // ⚠️ This asserts the DOM contract, NOT the appearance. `vite.config.ts`
    // does not enable `css` for vitest, so Svelte scoped styles never apply
    // under jsdom: a getComputedStyle comparison here would find BOTH groups at
    // browser defaults and pass vacuously. A shared class is the honest
    // jsdom-visible proxy for "one rule set, not two that can drift" — which is
    // F-16's stated preferred fix.
    mockGetListenPreview.mockResolvedValue(preview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("alle"));

    const tail = container.querySelector("details.tail-group")!;
    const known = container.querySelector("details.well-known-group")!;
    expect(tail).toBeTruthy();
    expect(known).toBeTruthy();

    // Svelte appends its own scoping class (svelte-xxxxxx) to both, which would
    // make a naive intersection pass trivially. Drop it.
    const classesOf = (el: Element) => [...el.classList].filter((c) => !c.startsWith("svelte-"));
    const shared = classesOf(tail).filter((c) => classesOf(known).includes(c));

    expect(
      shared.length,
      `tail=[${classesOf(tail)}] known=[${classesOf(known)}] share no styling class`,
    ).toBeGreaterThan(0);
  });
});
