/**
 * HASH-PINNED ORACLE for F-3 — the bulk buttons must not touch well-known rows.
 * Brief: bd tunatale-bh8 (closed)
 *
 * ⚠️ DO NOT EDIT THIS FILE while implementing. It is authored ahead of the
 * implementation on purpose: this is a SEMANTIC change, and an executor who
 * writes both the behaviour and its test can only prove the two agree with each
 * other. If an assertion here looks wrong, STOP and report it — do not adjust it
 * to match what you built.
 *
 * ── The report ────────────────────────────────────────────────────────
 *
 * User, 2026-08-04: "grade all adds in the known words but skip all doesn't
 * remove them; I think those buttons shouldn't affect known words either way."
 *
 * ── Why it is severe, not cosmetic ────────────────────────────────────
 *
 * A well-known row starts at 'skip'. `buildRatings` emits a well-known row
 * whenever it carries an explicit rating — the polarity is INVERTED for this
 * group, because the backend skips a well-known lemma that is ABSENT from
 * `word_ratings`, so presence there is the opt-in.
 *
 * So one press of Grade All stages EVERY known word, which defeats the whole
 * `listen_due_horizon_days` suppression feature — the feature exists precisely
 * so a listen stops asking about words scheduled beyond the horizon. And
 * `skipAll` iterates `liveCandidates`, which is filtered by `!c.well_known`, so
 * there is no bulk undo: the only escape is to cancel and reopen the modal.
 *
 * ── The contract ──────────────────────────────────────────────────────
 *
 * Neither bulk button touches a well-known row, in either direction. The known
 * group is opt-in PER ROW, only. `gradeAll` must skip `c.well_known === true`
 * the same way it already skips tail rows.
 *
 * Two things this must NOT do, both pinned below:
 *  - it must not disable the per-row opt-in (grading a known row by hand still
 *    sends an explicit rating), and
 *  - it must not stop Grade All working on ordinary rows.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, fireEvent, waitFor } from "@testing-library/svelte";
import ListenPreviewModal from "$lib/components/ListenPreviewModal.svelte";
import { api, type ListenPreviewCandidate } from "$lib/api";
import { listenCountdownPref } from "$lib/stores/listenCountdownPref.svelte";

vi.mock("$lib/api", () => ({
  api: {
    getListenPreview: vi.fn(),
    markAsListened: vi.fn(),
    getListens: vi.fn(),
  },
}));

vi.mock("$lib/stores/listened.svelte", async () => {
  const actual = await vi.importActual<typeof import("$lib/stores/listened.svelte")>(
    "$lib/stores/listened.svelte",
  );
  return { listenedStore: actual.listenedStore };
});

const mockGetListenPreview = vi.mocked(api.getListenPreview);
const mockMarkAsListened = vi.mocked(api.markAsListened);

beforeEach(() => {
  vi.clearAllMocks();
  vi.useRealTimers();
  listenCountdownPref.set("off");
});

// ── Fixtures ──────────────────────────────────────────────────────────

/** An ordinary due row: starts 'good', is what the bulk buttons are FOR. */
const dueCandidate = (text: string): ListenPreviewCandidate => ({
  kind: "word" as const,
  text,
  item_id: 42,
  grade_class: "due" as const,
  rating: "good" as const,
  translation: "",
  progress: 0.3,
  well_known: false,
  due_at: "2026-08-04T04:00:00+00:00",
  will_create: true,
});

/** A well-known row: scheduled far beyond the horizon, starts 'skip', and
 *  lives collapsed inside the known-words disclosure. */
const knownCandidate = (text: string): ListenPreviewCandidate => ({
  kind: "word" as const,
  text,
  item_id: 43,
  grade_class: "ahead" as const,
  rating: "good" as const,
  translation: "",
  progress: 0.95,
  deferred_reason: "known",
  well_known: true,
  due_at: "2126-01-01T04:00:00+00:00",
  will_create: true,
});

/** Two ordinary rows and two known ones — enough that a bulk action which
 *  wrongly sweeps the group in is visible as a COUNT, not just a flag. */
const mixedPreview = () => ({
  candidates: [
    dueCandidate("prosim"),
    dueCandidate("takk"),
    knownCandidate("hvala"),
    knownCandidate("bergen"),
  ],
});

const listenResult = {
  status: "ok",
  created: 0,
  staged: 0,
  applied: 0,
  remaining_candidates: 0,
  listen_count: 1,
};

const gradeBtn = (container: HTMLElement, key: string, grade: string) =>
  container.querySelector(
    `button[data-candidate='${key}'][data-grade='${grade}']`,
  ) as HTMLButtonElement;

const isActive = (b: HTMLButtonElement) => b.classList.contains("active");

const bulk = (container: HTMLElement, label: "Grade All" | "Skip All") =>
  [...container.querySelectorAll("button")].find((b) =>
    b.textContent?.includes(label),
  ) as HTMLButtonElement;

/** The word_ratings map actually sent to the API — the only thing that decides
 *  what the backend stages. DOM state is a proxy; this is the real contract. */
const sentWordRatings = () =>
  (mockMarkAsListened.mock.calls.at(-1)![1] ?? {}) as Record<string, string>;

const commit = async (container: HTMLElement) => {
  const btn = [...container.querySelectorAll("button")].find((b) =>
    /^Mark \d+ as listened$|^Mark as listened$/.test(b.textContent?.trim() ?? ""),
  ) as HTMLButtonElement;
  await fireEvent.click(btn);
};

// ── Tests ─────────────────────────────────────────────────────────────

describe("F-3 — bulk actions leave well-known rows alone", () => {
  it("Grade All does not promote a well-known row out of skip", async () => {
    mockGetListenPreview.mockResolvedValue(mixedPreview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("prosim"));

    await fireEvent.click(bulk(container, "Grade All"));

    // The known rows keep the 'skip' they were born with…
    expect(isActive(gradeBtn(container, "word:hvala", "skip"))).toBe(true);
    expect(isActive(gradeBtn(container, "word:bergen", "skip"))).toBe(true);
    expect(isActive(gradeBtn(container, "word:hvala", "good"))).toBe(false);

    // …while the ordinary rows are exactly what Grade All is for.
    expect(isActive(gradeBtn(container, "word:prosim", "good"))).toBe(true);
  });

  it("Grade All stages NOTHING from the known group — the payload, not the DOM", async () => {
    mockGetListenPreview.mockResolvedValue(mixedPreview());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("prosim"));

    await fireEvent.click(bulk(container, "Grade All"));
    await commit(container);

    await waitFor(() => {
      const wr = sentWordRatings();
      // 'skip' is the safe value here: the backend stages a well-known lemma
      // only when it carries a non-skip rating. What must NEVER appear is
      // 'good' — that is the bug, and it would stage all 20 known words.
      expect(wr["hvala"] ?? "skip").toBe("skip");
      expect(wr["bergen"] ?? "skip").toBe("skip");
      // The ordinary rows still went, or Grade All has been broken outright.
      expect(wr["prosim"] ?? "good").not.toBe("skip");
    });
  });

  it("Skip All leaves the known group untouched too — symmetry, both directions", async () => {
    mockGetListenPreview.mockResolvedValue(mixedPreview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("prosim"));

    await fireEvent.click(bulk(container, "Skip All"));

    expect(isActive(gradeBtn(container, "word:hvala", "skip"))).toBe(true);
    expect(isActive(gradeBtn(container, "word:prosim", "skip"))).toBe(true);
  });

  it("a Skip All → Grade All round trip never promotes a known row", async () => {
    // The round trip is where the old asymmetry actually bit: Grade All was
    // the only bulk action reaching the group, so repeating the pair walked
    // the known rows in and could not walk them back out.
    mockGetListenPreview.mockResolvedValue(mixedPreview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("prosim"));

    await fireEvent.click(bulk(container, "Skip All"));
    await fireEvent.click(bulk(container, "Grade All"));
    await fireEvent.click(bulk(container, "Skip All"));
    await fireEvent.click(bulk(container, "Grade All"));

    expect(isActive(gradeBtn(container, "word:hvala", "skip"))).toBe(true);
    expect(isActive(gradeBtn(container, "word:prosim", "good"))).toBe(true);
  });

  it("the PER-ROW opt-in still works, and Grade All does not undo it", async () => {
    // This is the assertion that stops the fix being "ignore well-known rows
    // everywhere". Grading one by hand is a real decision and must survive.
    mockGetListenPreview.mockResolvedValue(mixedPreview());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("prosim"));

    await fireEvent.click(gradeBtn(container, "word:hvala", "hard"));
    await fireEvent.click(bulk(container, "Grade All"));
    await commit(container);

    await waitFor(() => {
      const wr = sentWordRatings();
      expect(wr["hvala"]).toBe("hard"); // the hand-graded row, unchanged
      expect(wr["bergen"] ?? "skip").toBe("skip"); // its untouched neighbour
    });
  });

  it("selectedCount ignores the known group after Grade All", async () => {
    // The commit button's number is the user-visible tell. Two ordinary rows
    // are selected; the two known ones must not join them.
    mockGetListenPreview.mockResolvedValue(mixedPreview());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });
    await waitFor(() => getByText("prosim"));

    await fireEvent.click(bulk(container, "Grade All"));

    expect(getByText("Mark 2 as listened")).toBeTruthy();
  });
});
