/**
 * Orchestrator-authored contract for the over-budget creation tail.
 * Brief: docs/briefs/bp-listen-preview-creation-budget-ux-2026-07.md (Option B).
 *
 * ⚠️ DO NOT EDIT THIS FILE while implementing. It is authored ahead of the
 * implementation on purpose: this is NEW commit semantics, and an executor who
 * writes both the behavior and its test can only prove the two agree with each
 * other. If an assertion here looks wrong, STOP and report it — do not adjust it
 * to match what you built.
 *
 * The invariant under test (REVERSED 2026-07-31 by user decision, superseding
 * the promote-on-uncheck semantics this file pinned in `d589559`): skipping a
 * live create CONSUMES its budget slot. Nothing is promoted, so the server's
 * `will_create` flag stays correct no matter what the user checks and the
 * live/tail partition is STATIC. The modal must not re-derive it.
 *
 * What that buys: the preview becomes genuinely WYSIWYG. Skip All creates
 * nothing rather than quietly creating the next block of unseen lemmas; the
 * unspent daily-new headroom falls through to existing NEW cards via the queue
 * engine's `new_quota = cap - introduced_today`, which never counted creations.
 *
 * Backend companion: `backend/tests/test_api_listen_creation_skip_consumes_slot.py`.
 *
 * PRESENTATION CHANGE 2026-08-03 (user decision): the tail no longer hides
 * inside a collapsed `<details>`. It renders inline in the same list, dimmed,
 * tagged "next listen", under a line that states the cut. The complaint that
 * drove it: a disclosure is a hidden state, and "N more — next listen" implied
 * a decision the user could not act on. **Only the presentation assertions
 * moved.** Every semantic invariant above — skip consumes its slot, the tail is
 * read-only, the tail emits nothing on commit — is unchanged and still pinned
 * below. Marking tail rows as "skipped" was considered and REJECTED: `skip` is
 * a user decision that consumes a creation slot (`srs.py::mark_lesson_listened`,
 * `skipped_lemmas`), over-budget is a system state that consumes nothing, and
 * conflating them yields a control that either lies or silently does nothing.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, fireEvent, waitFor } from "@testing-library/svelte";
import ListenPreviewModal from "./ListenPreviewModal.svelte";
import { api, type ListenPreviewCandidate } from "$lib/api";
import { listenCountdownPref } from "$lib/stores/listenCountdownPref.svelte";

vi.mock("$lib/api", () => ({
  api: {
    getListenPreview: vi.fn(),
    markAsListened: vi.fn(),
    getListens: vi.fn(),
  },
}));

vi.mock("$lib/stores/listened.svelte", async () => {
  const actual = await vi.importActual<typeof import("$lib/stores/listened.svelte")>(
    "$lib/stores/listened.svelte",
  );
  return { listenedStore: actual.listenedStore };
});

const mockGetListenPreview = vi.mocked(api.getListenPreview);
const mockMarkAsListened = vi.mocked(api.markAsListened);

beforeEach(() => {
  vi.clearAllMocks();
  vi.useRealTimers();
  // The countdown auto-commits; every test here drives the commit itself.
  listenCountdownPref.set("off");
});

// ── Fixtures ──────────────────────────────────────────────────────────

/**
 * A create row. `will_create: false` is an over-budget (tail) row.
 *
 * The explicit `ListenPreviewCandidate` annotation is load-bearing: without it
 * TypeScript widens the returned literal and an unknown `will_create` sails
 * through structurally, so the field would not be pinned at the type level at
 * all. Annotated, this file does not compile until Step 1 adds the field.
 */
const createCandidate = (text: string, willCreate: boolean): ListenPreviewCandidate => ({
  kind: "create" as const,
  text,
  item_id: null,
  grade_class: "create" as const,
  rating: "good" as const,
  translation: "",
  progress: null,
  well_known: false,
  due_at: null,
  will_create: willCreate,
});

/**
 * The response shape Step 1 must produce: create rows first, in rank order,
 * live rows before tail rows. Budget = 2 here, tail = 3.
 */
const previewWithTail = () => ({
  candidates: [
    createCandidate("kake", true),
    createCandidate("melk", true),
    createCandidate("brød", false),
    createCandidate("smør", false),
    createCandidate("ost", false),
  ],
});

const listenResult = {
  status: "ok",
  created: 0,
  staged: 0,
  applied: 0,
  remaining_candidates: 0,
  listen_count: 1,
};

const gradeBtn = (container: HTMLElement, key: string, grade: string) =>
  container.querySelector(
    `button[data-candidate='${key}'][data-grade='${grade}']`,
  ) as HTMLButtonElement | null;

const isActive = (b: HTMLButtonElement) => b.classList.contains("active");

/** A tail row is dimmed, inline, and wears the "next listen" tag. */
const isTail = (container: HTMLElement, text: string) =>
  [...container.querySelectorAll("li.candidate.tail")].some(
    (li) => li.querySelector(".text")?.textContent === text,
  );

const tailTags = (container: HTMLElement) =>
  [...container.querySelectorAll("li.candidate.tail .tag.next-listen")].map((el) =>
    el.textContent?.trim(),
  );

/** A row is LIVE iff it carries the grade control; a tail row is read-only. */
const isLive = (container: HTMLElement, text: string) =>
  container.querySelector(`button[data-candidate='create:${text}']`) !== null;

// ── Tests ─────────────────────────────────────────────────────────────

describe("ListenPreviewModal — over-budget creation tail", () => {
  it("renders the tail read-only and INLINE — one flat list, no disclosure", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    // Live rows are gradeable; tail rows are rendered but carry no control.
    expect(isLive(container, "kake")).toBe(true);
    expect(isLive(container, "melk")).toBe(true);
    expect(isLive(container, "brød")).toBe(false);
    expect(isLive(container, "smør")).toBe(false);
    expect(isLive(container, "ost")).toBe(false);

    // Nothing is collapsed: the tail rows sit in the SAME <ul> as the live
    // rows. This is the whole point of the 2026-08-03 change — a <details>
    // the user must open is a hidden state.
    expect(container.querySelector("details.tail-group")).toBeNull();
    expect(container.querySelector(".tail-group")).toBeNull();

    const lists = container.querySelectorAll("ul.list");
    const rows = [...lists[0].querySelectorAll("li.candidate")].map(
      (li) => li.querySelector(".text")?.textContent,
    );
    expect(rows).toEqual(["kake", "melk", "brød", "smør", "ost"]);

    // Each held-back row says so on its own face, rather than being counted
    // in a summary the user has to expand to decode.
    expect(isTail(container, "brød")).toBe(true);
    expect(isTail(container, "ost")).toBe(true);
    expect(isTail(container, "kake")).toBe(false);
    expect(tailTags(container)).toEqual(["next listen", "next listen", "next listen"]);
  });

  it("states the cut instead of hiding it", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, queryByText } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    // 2 live introductions of 5 total; the reason is named, not implied.
    expect(getByText("Introducing 2 of 5 today — daily new-card limit")).toBeTruthy();
    // The old disclosure summary is gone for good.
    expect(queryByText(/more — next listen/)).toBeNull();
  });

  it("skipping a live create promotes NOTHING — the tail is static", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    await fireEvent.click(gradeBtn(container, "create:kake", "skip")!);

    // The whole point of the reversal: no tail row is pulled above the divider.
    await waitFor(() => {
      expect(isActive(gradeBtn(container, "create:kake", "skip")!)).toBe(true);
    });
    expect(isLive(container, "brød")).toBe(false);
    expect(isLive(container, "smør")).toBe(false);
    expect(isLive(container, "ost")).toBe(false);
    expect(isTail(container, "brød")).toBe(true);
    expect(getByText("Introducing 2 of 5 today — daily new-card limit")).toBeTruthy();

    // The skipped row stays live and stays skipped — legible and reversible.
    expect(isLive(container, "kake")).toBe(true);
  });

  it("the footer count drops when a create is skipped, because nothing replaces it", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => expect(getByText("Mark 2 as listened")).toBeTruthy());

    await fireEvent.click(gradeBtn(container, "create:kake", "skip")!);

    // Under promote-on-uncheck this stayed at 2. Now the slot is consumed and
    // the count must tell the truth about what the listen will create.
    await waitFor(() => expect(getByText("Mark 1 as listened")).toBeTruthy());
  });

  it("re-checking a skipped create restores the count without touching the tail", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    await fireEvent.click(gradeBtn(container, "create:kake", "skip")!);
    await waitFor(() => expect(getByText("Mark 1 as listened")).toBeTruthy());

    await fireEvent.click(gradeBtn(container, "create:kake", "good")!);

    await waitFor(() => expect(getByText("Mark 2 as listened")).toBeTruthy());
    expect(getByText("Introducing 2 of 5 today — daily new-card limit")).toBeTruthy();
    expect(isLive(container, "brød")).toBe(false);
  });

  it("sends nothing for tail rows — not 'skip', not 'good'", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("Mark 2 as listened"));
    await fireEvent.click(getByText("Mark 2 as listened"));

    await waitFor(() => {
      // Both live rows are default-good, so they are omitted too: an empty
      // word_ratings map is the correct payload for an untouched preview.
      //
      // ⚠️ Polarity trap, opposite to the well-known rows in the same function:
      // absent ⇒ the backend defaults to "good" and CREATES the card. A tail row
      // is outside the budget window so naming it is inert, but emitting "skip"
      // would still be wrong — it asserts a decision the user never made about a
      // row they were never offered.
      expect(mockMarkAsListened).toHaveBeenCalledWith("l1", {}, {}, [], []);
    });
  });

  it("sends 'skip' for an unchecked live row, and still nothing for the tail", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(gradeBtn(container, "create:kake", "skip")!);
    await fireEvent.click(getByText("Mark 1 as listened"));

    await waitFor(() => {
      // kake is named so the server consumes its slot without creating it.
      // melk stays default-good and is omitted. No tail row appears.
      expect(mockMarkAsListened).toHaveBeenCalledWith("l1", { kake: "skip" }, {}, [], []);
    });
  });

  it("Skip All names every live row and creates nothing", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());
    mockMarkAsListened.mockResolvedValue(listenResult);

    const { getByText } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(getByText("Skip All"));

    // Zero live creates remain, and the tail is untouched by the bulk action.
    await waitFor(() => expect(getByText("Mark as listened")).toBeTruthy());
    // The cut line is server state: skipping live rows does not move it.
    expect(getByText("Introducing 2 of 5 today — daily new-card limit")).toBeTruthy();

    await fireEvent.click(getByText("Mark as listened"));

    await waitFor(() => {
      expect(mockMarkAsListened).toHaveBeenCalledWith(
        "l1",
        { kake: "skip", melk: "skip" },
        {},
        [],
        [],
      );
    });
  });

  it("Grade All does not pull tail rows above the divider", async () => {
    mockGetListenPreview.mockResolvedValue(previewWithTail());

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));
    await fireEvent.click(getByText("Grade All"));

    await waitFor(() => expect(getByText("Mark 2 as listened")).toBeTruthy());
    expect(isLive(container, "brød")).toBe(false);
    expect(getByText("Introducing 2 of 5 today — daily new-card limit")).toBeTruthy();
  });

  it("a zero budget puts every create in the tail and grades none", async () => {
    // A same-day re-listen: new_cap already spent, creation_budget == 0.
    mockGetListenPreview.mockResolvedValue({
      candidates: [createCandidate("brød", false), createCandidate("smør", false)],
    });

    const { getByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("brød"));

    expect(isLive(container, "brød")).toBe(false);
    expect(isLive(container, "smør")).toBe(false);
    expect(getByText("Introducing 0 of 2 today — daily new-card limit")).toBeTruthy();
    expect(getByText("Mark as listened")).toBeTruthy();
  });

  it("shows no cut line when the budget covers everything", async () => {
    mockGetListenPreview.mockResolvedValue({
      candidates: [createCandidate("kake", true), createCandidate("melk", true)],
    });

    const { getByText, queryByText, container } = render(ListenPreviewModal, {
      props: { lessonId: "l1", onDone: vi.fn() },
    });

    await waitFor(() => getByText("kake"));

    expect(isLive(container, "kake")).toBe(true);
    expect(isLive(container, "melk")).toBe(true);
    expect(queryByText(/daily new-card limit/)).toBeNull();
    expect(container.querySelectorAll("li.candidate.tail")).toHaveLength(0);
  });
});
