"""Per-language DB isolation for the two remaining db-less resolver call sites.

⚠️ LOCKED ORACLE — do not edit this file to make an implementation pass. These
tests were written against the DEFECT, before the fix, and they are red on
purpose. If one fails, the implementation is wrong, not the test. Changing an
assertion here defeats the only external oracle this change has.

## The defect these pin (verified 2026-07-30, `8b93b31`)

`resolve_learning_steps`, `resolve_relearning_steps` and `resolve_fsrs_params`
are the 3 resolvers that still self-construct an ``SRSDatabase`` from
``settings.database_url`` when handed no db. Two live paths call them that way:

- ``app.srs.fsrs._get_steps_for_state`` (grading) -> learning/relearning steps
- ``app.srs.anki_mirror.queue_engine._merge_by_retrievability_ascending``
  (retrievability sort) -> FSRS params

``settings.database_url`` is the SINGULAR setting. In multi-language mode the
request's database comes from the PLURAL ``settings.database_urls[code]`` map
(see ``resolve_language_context``), and the repo's own dev ``.env`` sets
``DATABASE_URLS`` for both ``sl`` and ``no`` while leaving ``DATABASE_URL`` at
its ``tunatale_sl.db`` default. So a Norwegian grade reads SLOVENE learning
steps, and the Norwegian queue is sorted with SLOVENE FSRS params.

Measured, before the fix::

    per-language db (no) says: ([25.0, 55.0], 'cache')
    what the grading path calls: ([1.0, 10.0], 'cache')

This is the same hazard class ``app/api/srs.py`` already documents for the
lemmatizer ("a frozen import-time lemmatizer would analyze Norwegian
transcripts with the Slovene model") -- unfixed for these two.

## The required shape

Resolve in the caller that holds the db, then INJECT -- exactly how ``params``
and ``load_balancer`` already reach ``schedule()`` (``api/srs.py`` does
``resolve_fsrs_params(db)`` then passes it in), and how Layer 55 threaded the
live load balancer. Do NOT thread an ``SRSDatabase`` down into ``fsrs.py``;
it is pure scheduling logic and must stay that way.

``test_schedule_ignores_the_singular_database_url_setting`` and
``test_merge_ignores_the_singular_database_url_setting`` are the load-bearing
ones: they point ``settings.database_url`` at an unopenable path, so any
reintroduced db-less fallback yields hardcoded defaults instead of the injected
values and the assertion breaks. They are mechanism-agnostic -- they pin the
absence of the read, not the shape of the fix.

## ✅ GAP CLOSED 2026-08-03 -- see TestSingularSettingIsUnreachable at the foot

The gap described below was closed structurally rather than by adding the
wiring tests it asks for. The db-less fallbacks are gone: ``db`` is now a
REQUIRED parameter on all three resolvers, ``params`` is required on
``_merge_by_retrievability_ascending``, and ``fsrs._get_steps_for_state``
returns module constants instead of resolving a database. An unwired caller is
now a ``TypeError`` at the call site, so it cannot reach production, and the
inspection grep below is no longer the only thing standing between you and a
cross-language read. A checker (``scripts/check_singular_database_url.py``)
fails the gate on any new ``settings.database_url`` read outside the three
allowlisted readers.

The original text is kept below because the reasoning still explains WHY the
seam/wiring distinction matters when adding future oracles of this shape.

## ⚠️ KNOWN GAP IN THIS ORACLE (HISTORICAL -- closed, see above)

These tests pin the SEAM (the callee accepts and honours injected values). They
do NOT pin the WIRING (that the callers actually resolve from the request db and
pass it). An implementation that adds the parameters but leaves
``api/srs.py``'s grade sites and ``queue_engine._compute_live_main`` calling
without them turns this whole file green while the production bug survives
untouched.

Closing that gap needs a seeded-collocation fixture at the ``_compute_live_main``
/ route level, which is a bigger build than this file. Until it exists, the
wiring is verified by INSPECTION during audit -- both call sites must pass a
value resolved from the request's own db:

    grep -n "learn_steps=\\|relearn_steps=" app/api/srs.py     # 3 grade sites
    grep -n "params=" app/srs/anki_mirror/queue_engine.py      # _compute_live_main

Do not treat a green run here as proof the bug is fixed.

## Proven both ways before being handed off (2026-07-30)

Red without a fix (4 failures, all `TypeError: unexpected keyword argument`),
green under a throwaway implementation of the shape above (7 passed), then the
implementation was reverted so these ship red. An oracle that was never seen to
pass is as untrustworthy as one that was never seen to fail.
"""

import datetime
import json
from datetime import UTC, date, timedelta

import pytest

from app.models.srs_item import Direction, Rating, SRSItem, SRSState
from app.models.syntactic_unit import SyntacticUnit
from app.srs.database import SRSDatabase
from app.srs.fsrs import DEFAULT_FSRS5_PARAMS, schedule

_SL_LEARN_STEPS = [1.0, 10.0]
_NO_LEARN_STEPS = [25.0, 55.0]
_UNOPENABLE = "sqlite:////nonexistent/unopenable/dir/db.sqlite3"

# Anki fuzzes the interval around the nominal step (seeded per card, so it is
# deterministic per input -- 25.0 lands on 29.0 today). Assert a BAND, not the
# fuzzed value: pinning 29.0 would couple this oracle to fuzz internals and it
# would break on any legitimate fuzz change. The band's only job is to separate
# the Norwegian 25-min step from the Slovene 1-min one, which it does with room
# to spare.
_NO_FIRST_STEP_BAND = (15.0, 40.0)
_SL_FIRST_STEP_BAND = (0.5, 5.0)


def _fsrs_params_json(desired_retention: float) -> str:
    """A cache row shaped like `refresh_fsrs_params` writes it.

    NOTE: the resolver reads the ``fsrs_params`` JSON blob, NOT a bare
    ``desired_retention`` key. Seeding the wrong key makes BOTH languages fall
    back to the 0.9 default, at which point a "Slovene is 0.9" assertion passes
    for the wrong reason and the test cannot fail. Caught during authoring.
    """
    return json.dumps(
        {
            "weights": list(DEFAULT_FSRS5_PARAMS.weights),
            "desired_retention": desired_retention,
        }
    )


def _new_item(text: str = "dober dan") -> SRSItem:
    unit = SyntacticUnit(text=text, translation="good day", word_count=2, difficulty=1, source="corpus")
    return SRSItem(syntactic_unit=unit, due_date=date.today())


@pytest.fixture
def two_language_dbs(tmp_path, monkeypatch):
    """A Slovene and a Norwegian cache with DELIBERATELY different settings.

    Pins the plural map (the request path) and the singular setting (what the
    db-less fallback reads) at DIFFERENT databases -- that divergence is the
    whole point, and it mirrors the repo's real dev `.env`.
    """
    sl_path, no_path = tmp_path / "sl.db", tmp_path / "no.db"
    db_sl, db_no = SRSDatabase(str(sl_path)), SRSDatabase(str(no_path))

    db_sl.set_anki_state_cache("learn_steps", "[1.0, 10.0]")
    db_sl.set_anki_state_cache("relearn_steps", "[10.0]")
    db_sl.set_anki_state_cache("fsrs_params", _fsrs_params_json(0.85))

    db_no.set_anki_state_cache("learn_steps", "[25.0, 55.0]")
    db_no.set_anki_state_cache("relearn_steps", "[45.0]")
    db_no.set_anki_state_cache("fsrs_params", _fsrs_params_json(0.7))

    # Singular -> Slovene (this is what a db-less resolver call would read).
    # Plural -> both (this is what the request path actually uses).
    monkeypatch.setattr("app.srs.queue_stats.settings.database_url", f"sqlite:///{sl_path}")
    monkeypatch.setattr(
        "app.srs.queue_stats.settings.database_urls",
        {"sl": f"sqlite:///{sl_path}", "no": f"sqlite:///{no_path}"},
    )
    return db_sl, db_no


class TestResolversReadTheRequestDatabase:
    """The resolvers themselves are already correct WHEN GIVEN a db.

    These two pass today. They are here so the suite states the baseline the
    rest of the file builds on: the bug is never in the resolver, it is in the
    call sites that decline to pass it one.
    """

    def test_learning_steps_come_from_the_db_given(self, two_language_dbs):
        from app.srs.queue_stats import resolve_learning_steps

        db_sl, db_no = two_language_dbs
        assert resolve_learning_steps(db_sl) == (_SL_LEARN_STEPS, "cache")
        assert resolve_learning_steps(db_no) == (_NO_LEARN_STEPS, "cache")

    def test_fsrs_params_come_from_the_db_given(self, two_language_dbs):
        from app.srs.queue_stats import resolve_fsrs_params

        db_sl, db_no = two_language_dbs
        assert resolve_fsrs_params(db_sl)[0].desired_retention == pytest.approx(0.85)
        assert resolve_fsrs_params(db_no)[0].desired_retention == pytest.approx(0.7)


class TestGradingUsesTheRequestLanguageSteps:
    """`schedule()` must take its steps by injection, like `params`."""

    def test_schedule_accepts_injected_learning_steps(self, two_language_dbs):
        """A Norwegian grade must schedule on Norwegian steps, not Slovene's.

        First Norwegian learning step is 25 min vs Slovene's 1 min, so the
        resulting due_at is ~25 min out. Under the defect it is ~1 min out.
        """
        _, db_no = two_language_dbs
        from app.srs.queue_stats import resolve_learning_steps, resolve_relearning_steps

        learn_steps, _ = resolve_learning_steps(db_no)
        relearn_steps, _ = resolve_relearning_steps(db_no)

        now = datetime.datetime.now(UTC)
        result = schedule(
            _new_item(),
            Rating.AGAIN,
            now=now,
            learn_steps=learn_steps,
            relearn_steps=relearn_steps,
        )

        state = result.directions[Direction.RECOGNITION]
        assert state.state == SRSState.LEARNING
        delta_min = (state.due_at - now).total_seconds() / 60
        lo, hi = _NO_FIRST_STEP_BAND
        assert lo <= delta_min <= hi, (
            f"expected the fuzzed Norwegian first step ({lo}-{hi} min), got "
            f"{delta_min:.1f} min — the grading path is reading another "
            "language's learn_steps"
        )

    def test_schedule_ignores_the_singular_database_url_setting(self, two_language_dbs, monkeypatch):
        """LOAD-BEARING. `schedule()` must never open settings.database_url.

        Points the singular setting at an unopenable path. If a db-less
        fallback is ever reintroduced, it silently yields the hardcoded
        [1.0, 10.0] default and this assertion breaks. Mechanism-agnostic:
        it pins the absence of the read, not the shape of the fix.
        """
        monkeypatch.setattr("app.srs.queue_stats.settings.database_url", _UNOPENABLE)

        now = datetime.datetime.now(UTC)
        result = schedule(
            _new_item(),
            Rating.AGAIN,
            now=now,
            learn_steps=_NO_LEARN_STEPS,
            relearn_steps=[45.0],
        )

        state = result.directions[Direction.RECOGNITION]
        delta_min = (state.due_at - now).total_seconds() / 60
        lo, hi = _NO_FIRST_STEP_BAND
        assert lo <= delta_min <= hi, (
            f"expected {lo}-{hi} min from the INJECTED steps, got "
            f"{delta_min:.1f} min — schedule() fell back to settings.database_url"
        )

    def test_schedule_defaults_are_unchanged_when_nothing_is_injected(self):
        """Regression guard for single-language mode.

        Callers that inject nothing keep Anki's documented defaults, so the
        3 (of 4700) existing `schedule()` tests that pass no steps stay green.
        """
        now = datetime.datetime.now(UTC)
        result = schedule(_new_item(), Rating.AGAIN, now=now)

        state = result.directions[Direction.RECOGNITION]
        delta_min = (state.due_at - now).total_seconds() / 60
        lo, hi = _SL_FIRST_STEP_BAND
        assert lo <= delta_min <= hi


class TestQueueSortUsesTheRequestLanguageParams:
    """`_merge_by_retrievability_ascending` must take params by injection."""

    def _due_pair(self, db: SRSDatabase) -> tuple[list, list]:
        del db
        rec = [
            (1, self._review_item("prvi", stability=0.65), "no"),
            (2, self._review_item("drugi", stability=7.5), "no"),
        ]
        return rec, []

    @staticmethod
    def _review_item(text: str, *, stability: float) -> SRSItem:
        unit = SyntacticUnit(text=text, translation="x", word_count=1, difficulty=1, source="corpus")
        return SRSItem(
            syntactic_unit=unit,
            due_date=date.today(),
            stability=stability,
            difficulty=5.0,
            reps=3,
            state=SRSState.REVIEW,
            last_review=date.today() - timedelta(days=5),
        )

    def test_merge_accepts_injected_params(self, two_language_dbs):
        """The sort must run on the params it is handed, not a resolved global."""
        from app.srs.queue_engine import _merge_by_retrievability_ascending
        from app.srs.queue_stats import resolve_fsrs_params

        _, db_no = two_language_dbs
        params, _ = resolve_fsrs_params(db_no)
        rec, prod = self._due_pair(db_no)

        ordered = _merge_by_retrievability_ascending(rec, prod, date.today(), col_crt=None, params=params)

        assert [t[0] for t in ordered] == [1, 2], "retrievability-ascending must put the low-stability card first"

    def test_merge_ignores_the_singular_database_url_setting(self, two_language_dbs, monkeypatch):
        """LOAD-BEARING. The sort must never open settings.database_url.

        Same shape as the schedule() guard: an unopenable singular setting
        makes any reintroduced fallback observable.
        """
        from app.srs.queue_engine import _merge_by_retrievability_ascending
        from app.srs.queue_stats import resolve_fsrs_params

        _, db_no = two_language_dbs
        params, _ = resolve_fsrs_params(db_no)
        monkeypatch.setattr("app.srs.queue_stats.settings.database_url", _UNOPENABLE)

        rec, prod = self._due_pair(db_no)
        ordered = _merge_by_retrievability_ascending(rec, prod, date.today(), col_crt=None, params=params)

        assert [t[0] for t in ordered] == [1, 2]


class TestSingularSettingIsUnreachable:
    """Closes this file's KNOWN GAP structurally, rather than by inspection.

    The gap above is that these tests pin the SEAM (the callee honours injected
    values) but not the WIRING (that callers resolve from the request db and
    pass them) — an unwired caller silently fell through to
    ``settings.database_url``, the SINGULAR setting, which on a multi-language
    install is Slovene. That is how a Norwegian card got scheduled on Slovene
    steps (Layer 82), and the same read is what made
    ``grave_ignored_lemma_cards --language no`` report "Nothing to grave" for a
    month.

    The fix removes the fallback outright: ``db`` is required, so an unwired
    caller is a ``TypeError`` at the call site instead of a wrong answer. These
    tests pin the ABSENCE of the read, so they survive any reshaping of it.
    """

    @pytest.mark.parametrize(
        "func_name",
        ["resolve_fsrs_params", "resolve_learning_steps", "resolve_relearning_steps"],
    )
    def test_resolvers_require_a_database(self, func_name):
        from app.srs import queue_stats

        with pytest.raises(TypeError):
            getattr(queue_stats, func_name)()

    def test_merge_by_retrievability_requires_params(self):
        from app.srs.anki_mirror.queue_engine import _merge_by_retrievability_ascending

        with pytest.raises(TypeError):
            _merge_by_retrievability_ascending([], [], date.today())

    def test_schedule_without_injected_steps_never_reads_the_singular_db(self, two_language_dbs):
        """LOAD-BEARING, and it must FAIL before the fix.

        Most callers (and most tests) let ``schedule`` default its steps. The
        fixture seeds the singular setting with Slovene's 1-minute first step
        while the module default is also [1.0, 10.0] — indistinguishable. So
        re-point the singular at the NORWEGIAN db, whose 25-minute first step
        differs from the default: if the default still resolves from a
        database, the card lands in the 25-min band; if it comes from the
        module constant, it lands in the 1-min band.

        An unopenable path would NOT work here — the old resolver swallowed the
        connection error and returned the same defaults, so that version of this
        test passed before the fix and proved nothing.
        """
        _, db_no = two_language_dbs
        import app.srs.queue_stats as qs

        qs.settings.database_url = qs.settings.database_urls["no"]

        # AGAIN keeps the card on step 0, so this reads the FIRST step (1.0 min
        # default vs Norwegian's 25.0) and the bands below mean what they say.
        # GOOD would advance to step 1 and compare 10.0 against 55.0 instead —
        # still separated, but no longer "first step".
        updated = schedule(_new_item(), Rating.AGAIN, review_date=date.today())
        state = updated.directions[Direction.RECOGNITION]
        assert state.state is SRSState.LEARNING
        delta_min = (state.due_at - datetime.datetime.now(UTC)).total_seconds() / 60

        lo, hi = _SL_FIRST_STEP_BAND
        assert lo <= delta_min <= hi, (
            f"expected the module-default first step ({lo}-{hi} min), got {delta_min:.1f} min — "
            "schedule resolved its default steps from settings.database_url"
        )
