"""B1: the listen-preview must mirror mark_lesson_listened's ranked creation
list — and, since the Option-B tail landed, must DISCLOSE the over-budget
remainder rather than silently truncating it away.

Kept in a separate file from `test_api_listen_preview.py` on purpose: that
file's own docstring pins it as an untouched Stage-4 guard-test contract
("Do NOT edit these tests — git diff on this file must be empty at
delivery. Add separate tests for any extra coverage you need."). These tests
exercise the budget/ranking behavior layered on top of that contract.

⚠️ REWRITTEN 2026-07-31 by the orchestrator for the creation-tail brief
(bd `tunatale-tsq`, closed). The previous
version asserted the OLD contract, where over-budget lemmas were absent from the
response entirely (`creates == []`, `len(creates) == 3`). Under Option B every
untracked lemma is returned in rank order and `will_create` distinguishes the
live rows from the tail, so "truncation" is now a property of the FLAG, not of
the list. Executors: do not edit this file — it is the oracle for the change you
are implementing. If an assertion looks wrong, STOP and report.
"""

from __future__ import annotations

from httpx import ASGITransport, AsyncClient

from app.main import app
from app.models.lesson import Lesson, Phrase, Section, SectionType
from app.models.srs_item import Direction, SRSState
from app.models.syntactic_unit import SyntacticUnit
from tests._helpers.api_app_state import _clean_app_state  # noqa: F401

PREVIEW_URL = "/api/srs/lesson/lesson-1/listen-preview"
LISTEN_URL = "/api/srs/listen"


def _setup(phrases: list[str], language_code: str = "sl"):
    from app.srs.database import SRSDatabase
    from app.storage.store import ContentStore

    lesson = Lesson(
        title="Day 1",
        language_code=language_code,
        sections=[
            Section(
                section_type=SectionType.NATURAL_SPEED,
                phrases=[
                    Phrase(text=t, voice_id="female-1", language_code=language_code, role="female-1") for t in phrases
                ],
            )
        ],
        key_phrases=[],
    )
    db = SRSDatabase(":memory:")
    store = ContentStore(":memory:")
    store.save_lesson("lesson-1", "curriculum-1", 1, lesson)
    app.state.srs_db = db
    app.state.content_store = store
    return db


def _seed_review_due(db, text: str, *, days_overdue: int = 1) -> None:
    from datetime import UTC, datetime, timedelta

    from app.srs.anki_mirror.rollover import anki_today, due_at_rollover_utc

    unit = SyntacticUnit(text=text, translation=f"t-{text}", word_count=1, difficulty=1, source="test")
    db.add_collocation(unit, language_code="sl")
    item = db.get_collocation(text)
    rec = item.directions[Direction.RECOGNITION]
    rec.state = SRSState.REVIEW
    rec.last_review = datetime.now(UTC) - timedelta(days=5)
    rec.due_at = due_at_rollover_utc(anki_today() - timedelta(days=days_overdue))
    rec.reps = 5
    db.update_collocation(item)


async def _get_preview() -> dict:
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.get(PREVIEW_URL)
    assert resp.status_code == 200
    return resp.json()


async def _post_listen(payload: dict) -> dict:
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post(LISTEN_URL, json=payload)
    assert resp.status_code == 200
    return resp.json()


def _creates(preview: dict) -> list[dict]:
    return [c for c in preview["candidates"] if c["kind"] == "create"]


def _live(preview: dict) -> list[str]:
    """Texts of the create rows this listen would actually create."""
    return [c["text"] for c in _creates(preview) if c["will_create"]]


def _tail(preview: dict) -> list[str]:
    """Texts of the disclosed-but-over-budget create rows."""
    return [c["text"] for c in _creates(preview) if not c["will_create"]]


class TestPreviewMatchesListenCreation:
    async def test_preview_create_set_equals_actual_listen_creations(self):
        """The point of B1, restated for the tail: what the preview flags
        `will_create` must be exactly what a listen against the same state WOULD
        create. The tail rows are disclosure only and must NOT be created."""
        lemmas = ["banka", "center", "hotel", "kava", "mesto"]
        db = _setup([" ".join(lemmas)])
        db.set_anki_state_cache("daily_new_cap", "2")

        preview = await _get_preview()
        preview_live = set(_live(preview))

        listen = await _post_listen({"lesson_id": "lesson-1"})
        assert listen["created"] == 2

        created_texts = {lemma for lemma in lemmas if db.get_collocation_by_lemma(lemma) is not None}
        assert preview_live == created_texts
        assert len(preview_live) == 2

        # The tail is the complement, and none of it reached the database.
        tail = set(_tail(preview))
        assert tail == set(lemmas) - created_texts
        assert tail, "a cap of 2 against 5 untracked lemmas must leave a tail"


class TestPreviewDisclosesTheTail:
    async def test_every_untracked_lemma_is_returned_with_only_the_budget_flagged(self):
        """Un-truncation: the response carries all 5, flagged 3 live / 2 tail.
        The old contract returned 3 rows and dropped the rest on the floor."""
        lemmas = ["banka", "center", "hotel", "kava", "mesto"]
        db = _setup([" ".join(lemmas)])
        db.set_anki_state_cache("daily_new_cap", "3")

        preview = await _get_preview()

        assert len(_creates(preview)) == 5
        assert len(_live(preview)) == 3
        assert len(_tail(preview)) == 2

    async def test_live_rows_precede_tail_rows_in_the_response(self):
        """Array-order contract the frontend derivation depends on: create rows
        come first, in rank order, live before tail. A client that partitions on
        the flag must find the two blocks contiguous."""
        db = _setup(["hotel kava banka kava banka banka center mesto"])
        db.set_anki_state_cache("daily_new_cap", "2")

        preview = await _get_preview()
        flags = [c["will_create"] for c in _creates(preview)]

        assert flags == sorted(flags, reverse=True), f"live/tail rows interleaved: {flags}"


class TestPreviewBudgetExhausted:
    async def test_zero_budget_flags_nothing_live_but_still_discloses(self):
        db = _setup(["banka riba"])
        _seed_review_due(db, "riba")
        db.set_anki_state_cache("daily_new_cap", "0")

        preview = await _get_preview()
        tracked = [c for c in preview["candidates"] if c["kind"] != "create"]

        assert _live(preview) == []
        assert _tail(preview) == ["banka"], "a zero budget discloses the tail, it does not hide it"
        assert any(c["text"] == "riba" for c in tracked)

    async def test_same_day_relisten_flags_nothing_live(self):
        """Same-day-re-listen case: count_new_created_today already at cap."""
        lemmas = ["banka", "center", "hotel"]
        db = _setup([" ".join(lemmas)])
        db.set_anki_state_cache("daily_new_cap", "1")

        first = await _post_listen({"lesson_id": "lesson-1"})
        assert first["created"] == 1

        preview = await _get_preview()
        assert _live(preview) == [], "budget already spent today by the first listen's creation"
        assert len(_tail(preview)) == 2, "the two lemmas it did not create are still disclosed"


class TestPreviewCreateOrder:
    async def test_create_rows_are_in_rank_order_not_analysis_order(self):
        """Rank order is not analysis (first-appearance) order.

        Updated 2026-08-03: ranking is corpus frequency, not occurrence count.
        First-appearance order is hotel, kava, banka; zipf(sl) is hotel 4.98,
        banka 4.39, kava 4.09, so the ranked order is hotel, banka, kava.
        Budget=2 flags the two commonest — and the tail continues the same
        ranking rather than reverting to analysis order. The discrimination
        survives the swap: analysis order would put kava live and banka in the
        tail, which is exactly what this asserts against."""
        db = _setup(["hotel kava banka kava banka banka"])
        db.set_anki_state_cache("daily_new_cap", "2")

        preview = await _get_preview()

        assert _live(preview) == ["hotel", "banka"], f"expected ranked order, got {_live(preview)}"
        assert _tail(preview) == ["kava"]
