/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/admin/refresh-media": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh Media
     * @description Re-import media from Anki, updating changed files (SHA-aware).
     *
     *     Returns counts: {updated, unchanged, new, errors}.
     */
    post: operations["refresh_media_api_admin_refresh_media_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/anki/peer-sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Trigger Peer Sync
     * @description Sync TT's own collection to AnkiWeb (or a self-host server) as a peer.
     *
     *     Touches TT's own ``tt_collection`` and works with Anki open. Returns
     *     409 with a user-facing message if peer-sync isn't configured (e.g. no credential in
     *     the macOS Keychain) or if the server demands a full sync.
     *
     *     Generates media (audio/images) for any TT-added cards via the media generator,
     *     so they reach AnkiWeb with media attached.
     */
    post: operations["trigger_peer_sync_api_anki_peer_sync_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/audio/lesson/{lesson_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Lesson Audio
     * @description Return the audio file list for a lesson (full + sections) without re-rendering.
     */
    get: operations["get_lesson_audio_api_audio_lesson__lesson_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/audio/lesson/{lesson_id}/zip": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download Lesson Zip
     * @description Return a ZIP of all section WAVs for a lesson with context-rich filenames.
     */
    get: operations["download_lesson_zip_api_audio_lesson__lesson_id__zip_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/audio/render": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Render Audio */
    post: operations["render_audio_api_audio_render_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/audio/{audio_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Audio */
    get: operations["get_audio_api_audio__audio_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Curricula */
    get: operations["list_curricula_api_curriculum_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Curriculum Plan */
    post: operations["import_curriculum_plan_api_curriculum_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Plan
     * @description LLM-free: mint an id and save an empty curriculum with empty planner state.
     */
    post: operations["start_plan_api_curriculum_plan_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Curriculum */
    get: operations["get_curriculum_api_curriculum__curriculum_id__get"];
    put?: never;
    post?: never;
    /** Delete Curriculum */
    delete: operations["delete_curriculum_api_curriculum__curriculum_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/days/{day}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Day
     * @description Delete a committed day: its lessons/audio are removed, the day itself is
     *     dropped from ``curriculum.days`` (no renumbering of later days). Existing
     *     SRS/Anki cards from a deleted lesson are untouched.
     */
    delete: operations["delete_day_api_curriculum__curriculum_id__days__day__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/days/{day}/lesson": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Lesson By Day */
    get: operations["get_lesson_by_day_api_curriculum__curriculum_id__days__day__lesson_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/generation-mode": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Set Generation Mode
     * @description Set the generation mode for a curriculum: 'auto' (default, Groq pipeline) or 'manual' (copy/paste).
     */
    post: operations["set_generation_mode_api_curriculum__curriculum_id__generation_mode_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/pipeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Pipeline Status */
    get: operations["pipeline_status_api_curriculum__curriculum_id__pipeline_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/pipeline/regenerate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pipeline Regenerate */
    post: operations["pipeline_regenerate_api_curriculum__curriculum_id__pipeline_regenerate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/pipeline/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pipeline Retry */
    post: operations["pipeline_retry_api_curriculum__curriculum_id__pipeline_retry_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/plan/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Plan Commit
     * @description Append the proposed batch to the committed days and clear the proposal.
     */
    post: operations["plan_commit_api_curriculum__curriculum_id__plan_commit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/plan/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Plan Feedback
     * @description Record listening feedback for a committed day; it enters the next turn's prompt.
     */
    post: operations["plan_feedback_api_curriculum__curriculum_id__plan_feedback_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/plan/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Plan Reset
     * @description Clear the planner chat and proposed batch (keeps feedback and committed days).
     */
    post: operations["plan_reset_api_curriculum__curriculum_id__plan_reset_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/plan/turn": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Plan Turn
     * @description One planner chat turn: snapshot → LLM / pasted response → append chat, set/replace proposed.
     */
    post: operations["plan_turn_api_curriculum__curriculum_id__plan_turn_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/plan/turn/prompt": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Plan Turn Prompt
     * @description Export the exact prompts for a planner turn, without calling any LLM.
     *
     *     The system and user prompts returned are byte-identical to what the
     *     Groq path would send for the same inputs.  Persists nothing.
     */
    post: operations["plan_turn_prompt_api_curriculum__curriculum_id__plan_turn_prompt_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Curriculum Progress */
    get: operations["get_curriculum_progress_api_curriculum__curriculum_id__progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/curriculum/{curriculum_id}/source": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Curriculum Source */
    get: operations["get_curriculum_source_api_curriculum__curriculum_id__source_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/languages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Languages
     * @description Configured languages (for the frontend selector) + the request's active one.
     *
     *     Lists every language with an open connection; single-language deployments
     *     return one entry. ``active`` is the language the X-TT-Language header resolved
     *     to for this request.
     */
    get: operations["languages_api_languages_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Llm Activity */
    get: operations["llm_activity_api_llm_activity_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Llm Health */
    get: operations["llm_health_api_llm_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/rate-limit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rate Limit Status */
    get: operations["rate_limit_status_api_llm_rate_limit_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/llm/rate-limit/probe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rate Limit Probe */
    post: operations["rate_limit_probe_api_llm_rate_limit_probe_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/backfill-translations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Backfill Translations
     * @description One-time repair: fill empty translations from all stored lesson glosses.
     */
    post: operations["backfill_translations_api_srs_backfill_translations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/due": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Due Collocations */
    get: operations["get_due_collocations_api_srs_due_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/ignored-lemmas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Ignored Lemma */
    post: operations["add_ignored_lemma_api_srs_ignored_lemmas_post"];
    /** Remove Ignored Lemma */
    delete: operations["remove_ignored_lemma_api_srs_ignored_lemmas_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/inflection-clozes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Inflection Cloze
     * @description Create one morphology cloze for an inflected surface (Phase 4a).
     *
     *     Gated on the lemma's base production being in REVIEW or KNOWN.
     *     Idempotent by guid. Follows the add_collocation contract
     *     (card_type=cloze, no Anki ids).
     */
    post: operations["create_inflection_cloze_api_srs_inflection_clozes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Items */
    get: operations["list_items_api_srs_items_get"];
    put?: never;
    /** Create Item */
    post: operations["create_item_api_srs_items_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/base": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Base Card
     * @description Create a base card for an unknown clicked word (Phase 5, Part C / decision 8, C-a).
     *
     *     Branches by word type (the word-learning state machine):
     *       - function word → production-only cloze (the *surface* blanked in the sentence)
     *       - content word  → vocab (recognition + production)
     *     Both created in NEW state. Idempotent by the base guid. Honors the
     *     add_collocation card-adding contract (no Anki ids; sync_create_new mints +
     *     links). No LLM auto-translate here — the caller passes the transcript gloss.
     */
    post: operations["create_base_card_api_srs_items_base_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/bulk-delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bulk Delete Items */
    post: operations["bulk_delete_items_api_srs_items_bulk_delete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Item */
    delete: operations["delete_item_api_srs_items__item_id__delete"];
    options?: never;
    head?: never;
    /** Patch Item */
    patch: operations["patch_item_api_srs_items__item_id__patch"];
    trace?: never;
  };
  "/api/srs/items/{item_id}/direction/{direction}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Drill Feedback */
    post: operations["drill_feedback_api_srs_items__item_id__direction__direction__feedback_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}/direction/{direction}/undo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Undo Grade
     * @description Undo the most recent TT-native grade on (item, direction).
     *
     *     409 when the grade was superseded by a newer one, already synced to Anki
     *     (dirty_fsrs cleared), or there is nothing to undo.
     */
    post: operations["undo_grade_api_srs_items__item_id__direction__direction__undo_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}/image": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Put Image From Url */
    put: operations["put_image_from_url_api_srs_items__item_id__image_put"];
    post?: never;
    /** Delete Image */
    delete: operations["delete_image_api_srs_items__item_id__image_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}/image/candidates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Image Candidates */
    get: operations["get_image_candidates_api_srs_items__item_id__image_candidates_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}/image/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Put Image Upload */
    put: operations["put_image_upload_api_srs_items__item_id__image_upload_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset Item */
    post: operations["reset_item_api_srs_items__item_id__reset_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}/restore-known": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restore Known Item
     * @description Reverse a "Mark known" — restore the snapshotted pre-known schedule.
     *
     *     Dedicated rather than overloading set_item_state: the "review"/"new" state
     *     mappings there are label-only / full-reset and would be confusing here.
     *     No-op (still 200) when the item has no known snapshot.
     */
    post: operations["restore_known_item_api_srs_items__item_id__restore_known_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Set Item State */
    post: operations["set_item_state_api_srs_items__item_id__state_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}/suspend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Suspend Item */
    post: operations["suspend_item_api_srs_items__item_id__suspend_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/items/{item_id}/untrack": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Untrack Item */
    post: operations["untrack_item_api_srs_items__item_id__untrack_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/lesson/{lesson_id}/commit-pending": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Commit Pending Grades
     * @description Bulk "Sync it": release every staged grade for a lesson without reviewing it.
     *
     *     Applies each pending row at its provisional rating through the SAME path a
     *     per-card release takes (``schedule`` → revlog → ``dirty_fsrs``), then clears
     *     it. Afterwards these are ordinary dirty grades and the next normal "Sync to
     *     AnkiWeb" pushes them — this endpoint deliberately does NOT sync by itself.
     *
     *     One shared balancer and a monotonic grade clock across the batch, exactly as
     *     the pre-staging /listen grade loop had: ``tt_revlog.id`` is a millisecond PK
     *     and ``append_revlog`` is INSERT OR IGNORE, so two grades in the same
     *     millisecond would silently drop one.
     */
    post: operations["commit_pending_grades_api_srs_lesson__lesson_id__commit_pending_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/lesson/{lesson_id}/listen-preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Listen Preview
     * @description Read-only classification of what a listen would stage for a lesson.
     *
     *     The ``create`` rows are exactly what a listen against this same state
     *     would create RIGHT NOW: untracked lemmas ranked by
     *     ``_rank_listen_candidates`` and truncated to the same per-listen creation
     *     budget ``mark_lesson_listened`` uses (``resolve_daily_new_cap`` minus
     *     today's introductions and still-NEW same-day creations). Without this the
     *     preview and the commit disagree — a same-day re-listen has ~0 budget left
     *     and would create nothing even though the preview showed every untracked
     *     lemma as checked.
     *
     *     Tracked word/kp candidates are unchanged: creations first, then tracked by
     *     mastery ascending (least-known first). Strictly read-only — no pending
     *     writes, no card creation, no side effects beyond the
     *     ``_analyze_lesson_words`` lemma-cache warm-up. The response informs the
     *     frontend preview modal without committing anything.
     *
     *     Residual divergence (documented, not fixed here): if the user unchecks a
     *     shown create row before committing, the commit re-ranks over the
     *     remaining untracked set and may create a DIFFERENT lemma the preview never
     *     showed — the budget is spent by rank order, not by row identity.
     */
    get: operations["get_listen_preview_api_srs_lesson__lesson_id__listen_preview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/lesson/{lesson_id}/review-queue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Lesson Review Queue
     * @description Lesson-scoped "Check your work" queue: exactly the listen's autograded cards.
     *
     *     Items share ``_queue_item_to_dict``'s shape with /review-queue; grading a
     *     served item goes through the normal per-item feedback endpoint (an Again
     *     on an auto-Good'ed card is an ordinary same-day lapse). Strictly
     *     read-only w.r.t. parity state: no learning-cutoff advance, no
     *     session_main_queue write, no unbury sweep, no queue-engine involvement —
     *     the frozen main-queue order must survive this endpoint unchanged (pinned
     *     by the parity-guard test).
     *
     *     Inclusion is now exactly this lesson's ``pending_listen_grades`` rows, so
     *     the served queue and what "Sync it" (``commit-pending``) would release are
     *     the same set by construction — they are read from the same query. Scoping
     *     narrowed here 2026-07-27; the endpoint used to be a lesson-scoped *study*
     *     queue (D6 buckets: learning, tracked NEW in D2 rank order, REVIEW
     *     touched-today or due). After the confirmed/staged split that produced two
     *     visible wrongs: cards the user had just confirmed in the preview came back
     *     (applied immediately, so no pending row, but re-admitted by "touched
     *     today" — the double-question the split existed to remove), and due *cloze*
     *     cards appeared that a listen can never autograde, since staging is
     *     RECOGNITION-only and cloze is production-only. Everything dropped stays
     *     reachable from the main queue: with no pending row, the Layer 81 exclusion
     *     does not hold it back.
     *
     *     Consequences worth knowing: a NEW card can never appear (``_listen_grade_class``
     *     returns None for NEW, so nothing stages it), and neither can a cloze. Release
     *     by any path — per-card grade, ``commit-pending``, or an Anki-side grade
     *     arriving via ``sync_pull`` — clears the row, which is what drops the card
     *     from this queue; no separate "graded since the arming listen" filter is
     *     needed.
     */
    get: operations["get_lesson_review_queue_api_srs_lesson__lesson_id__review_queue_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/lesson/{lesson_id}/reviewed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark Lesson Reviewed
     * @description Record completion of a lesson-scoped 'Check your work' review.
     *
     *     Gates the lesson page's "Check your work" link to one-shot-per-listen:
     *     a completed review clears the link until the next listen re-arms it
     *     (has_unreviewed_listen on the review-queue response). TT-only; touches
     *     no parity/FSRS state.
     */
    post: operations["mark_lesson_reviewed_api_srs_lesson__lesson_id__reviewed_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/lesson/{lesson_id}/transcript": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Lesson Transcript */
    get: operations["get_lesson_transcript_api_srs_lesson__lesson_id__transcript_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/listen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark Lesson Listened */
    post: operations["mark_lesson_listened_api_srs_listen_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/listens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Listens */
    get: operations["get_listens_api_srs_listens_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/listens/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Listens */
    post: operations["import_listens_api_srs_listens_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/media/{filename}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Serve Media */
    get: operations["serve_media_api_srs_media__filename__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/new": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get New Collocations */
    get: operations["get_new_collocations_api_srs_new_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/queue-stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Queue Stats */
    get: operations["get_queue_stats_api_srs_queue_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/review-queue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Review Queue
     * @description Return the entire ordered review queue in one shot.
     *
     *     Implements Anki's queue construction: combined new-card cap across directions,
     *     sibling burying, and newSpread ordering.
     *
     *     `session_start=1` is the deck-open analog: it advances `learning_cutoff` to
     *     `now` so any learning card whose timer has elapsed since the last grade jumps
     *     into `ready_learning`. Frontend passes it on page mount (= deck open). Other
     *     callers (per-grade refetch, polling) leave it false to preserve the frozen
     *     cutoff between grades. Mirrors Anki's `update_learning_cutoff_and_count`
     *     being called at queue build time (rslib scheduler/queue/builder/mod.rs:222).
     */
    get: operations["get_review_queue_api_srs_review_queue_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Stats */
    get: operations["get_stats_api_srs_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/translate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Translate */
    post: operations["translate_api_srs_translate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/srs/translate-missing": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Translate Missing
     * @description Call the LLM to fill in translations for every card that has none.
     */
    post: operations["translate_missing_api_srs_translate_missing_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/story/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate Story */
    post: operations["generate_story_api_story_generate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/story/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import Story
     * @description Rebuild a Lesson from an edited Story-JSON file (docs/lesson-authoring.md).
     *
     *     Same shape as generate_story's response, plus `warnings` (e.g. a speaker
     *     missing from the voice map, which would silently fall back to the narrator).
     */
    post: operations["import_story_api_story_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/story/prompt": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Story Prompt
     * @description Export the exact prompts that the generate path would send to the LLM.
     */
    get: operations["get_story_prompt_api_story_prompt_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/story/{lesson_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Lesson */
    get: operations["get_lesson_api_story__lesson_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/story/{lesson_id}/source": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Lesson Source
     * @description Export a lesson as its editable, self-describing Story-JSON file.
     */
    get: operations["get_lesson_source_api_story__lesson_id__source_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_put_image_upload_api_srs_items__item_id__image_upload_put */
    Body_put_image_upload_api_srs_items__item_id__image_upload_put: {
      /** File */
      file: string;
    };
    /** BulkDeleteRequest */
    BulkDeleteRequest: {
      /** Ids */
      ids: number[];
    };
    /**
     * CommitPendingResponse
     * @description Response of POST /lesson/{id}/commit-pending.
     */
    CommitPendingResponse: {
      /** Applied */
      applied: number;
      /** Status */
      status: string;
    };
    /** CreateBaseCardRequest */
    CreateBaseCardRequest: {
      /** Language Code */
      language_code: string;
      /** Lemma */
      lemma: string;
      /** Sentence */
      sentence: string;
      /** Surface */
      surface: string;
      /**
       * Translation
       * @default
       */
      translation: string;
    };
    /** CreateItemRequest */
    CreateItemRequest: {
      /** Language Code */
      language_code: string;
      /** Source Lesson Id */
      source_lesson_id?: string | null;
      /** Source Line Index */
      source_line_index?: number | null;
      /**
       * Source Sentence
       * @default
       */
      source_sentence: string;
      /** Text */
      text: string;
      /**
       * Translation
       * @default
       */
      translation: string;
      /** Word Count */
      word_count: number;
    };
    /**
     * DeleteCurriculumResponse
     * @description Response of DELETE /api/curriculum/{curriculum_id}.
     */
    DeleteCurriculumResponse: {
      /** Deleted */
      deleted: string;
    };
    /**
     * DeleteDayResponse
     * @description Response of DELETE /api/curriculum/{curriculum_id}/days/{day}.
     */
    DeleteDayResponse: {
      /** Days */
      days: number;
      /** Deleted Day */
      deleted_day: number;
    };
    /** DrillRequest */
    DrillRequest: {
      /**
       * Lesson Review
       * @default false
       */
      lesson_review: boolean;
      /** Rating */
      rating?: string | null;
      /** Signal */
      signal?: string | null;
      /**
       * Time Ms
       * @default 0
       */
      time_ms: number;
    };
    /** GenerateStoryRequest */
    GenerateStoryRequest: {
      /** Curriculum Id */
      curriculum_id: string;
      /**
       * Day
       * @default 1
       */
      day: number;
      /**
       * Strategy
       * @default WIDER
       * @enum {string}
       */
      strategy: "WIDER" | "DEEPER";
    };
    /**
     * GenerateStoryResponse
     * @description Response of POST /api/story/generate.
     */
    GenerateStoryResponse: {
      /** Id */
      id: string;
      /** Sections */
      sections: unknown[];
      /** Title */
      title: string;
    };
    /** GenerationModeRequest */
    GenerationModeRequest: {
      /**
       * Mode
       * @enum {string}
       */
      mode: "auto" | "manual";
    };
    /**
     * GetLessonAudioResponse
     * @description Response of GET /api/audio/lesson/{lesson_id}.
     */
    GetLessonAudioResponse: {
      /** Audio Id */
      audio_id: string;
      /** Cues */
      cues?: unknown[] | null;
      /** Lesson Id */
      lesson_id: string;
      /** Sections */
      sections: unknown[];
    };
    /**
     * GetStoryPromptResponse
     * @description Response of GET /api/story/prompt.
     */
    GetStoryPromptResponse: {
      /** System Prompt */
      system_prompt: string;
      /** User Prompt */
      user_prompt: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description Response of GET /api/health.
     */
    HealthResponse: {
      /** Status */
      status: string;
    };
    /** IgnoreLemmaRequest */
    IgnoreLemmaRequest: {
      /** Language Code */
      language_code: string;
      /** Lemma */
      lemma: string;
    };
    /**
     * ImportCurriculumPlanResponse
     * @description Response of POST /api/curriculum/import.
     */
    ImportCurriculumPlanResponse: {
      /** Days */
      days: number;
      /** Id */
      id: string;
      /** Language Code */
      language_code: string;
      /** Topic */
      topic: string;
    };
    /**
     * ImportLessonRequest
     * @description Self-describing Story-JSON file (docs/lesson-authoring.md).
     *
     *     Provide exactly one of ``story`` (pre-parsed dict) or ``raw`` (pasted text
     *     containing prose + fenced JSON, cleaned via ``parse_json_object``).
     */
    ImportLessonRequest: {
      /** Curriculum Id */
      curriculum_id: string;
      /** Day */
      day: number;
      /** Raw */
      raw?: string | null;
      /** Story */
      story?: {
        [key: string]: unknown;
      } | null;
    };
    /** ImportListensRequest */
    ImportListensRequest: {
      /** Lesson Ids */
      lesson_ids: string[];
    };
    /**
     * ImportPlanRequest
     * @description Self-describing plan file for curriculum authoring.
     *
     *     ``days`` stays a free list — its schema is validated by
     *     ``plan_io.validate_plan_days`` so errors carry field paths.
     */
    ImportPlanRequest: {
      /** Cefr Level */
      cefr_level: string;
      /** Days */
      days: unknown[];
      /** Id */
      id?: string | null;
      /** Language Code */
      language_code: string;
      /** Topic */
      topic: string;
    };
    /** InflectionClozeRequest */
    InflectionClozeRequest: {
      /** Feature */
      feature: string;
      /** Language Code */
      language_code: string;
      /** Lemma */
      lemma: string;
      /**
       * Lesson Id
       * @default
       */
      lesson_id: string;
      /** Sentence */
      sentence: string;
      /** Surface */
      surface: string;
      /**
       * Translation
       * @default
       */
      translation: string;
    };
    /**
     * ListenPreviewCandidate
     * @description One row of GET /lesson/{id}/listen-preview's response.
     */
    ListenPreviewCandidate: {
      /** Due At */
      due_at?: string | null;
      /**
       * Grade Class
       * @enum {string}
       */
      grade_class: "create" | "learning" | "due" | "ahead";
      /** Item Id */
      item_id: number | null;
      /**
       * Kind
       * @enum {string}
       */
      kind: "create" | "word" | "kp";
      /** Progress */
      progress: number | null;
      /**
       * Rating
       * @enum {string}
       */
      rating: "again" | "hard" | "good" | "easy" | "skip";
      /** Text */
      text: string;
      /** Translation */
      translation: string;
      /**
       * Well Known
       * @default false
       */
      well_known: boolean;
    };
    /**
     * ListenPreviewResponse
     * @description Response of GET /lesson/{id}/listen-preview.
     */
    ListenPreviewResponse: {
      /** Candidates */
      candidates: components["schemas"]["ListenPreviewCandidate"][];
    };
    /** ListenRequest */
    ListenRequest: {
      /**
       * Confirmed Kps
       * @default []
       */
      confirmed_kps: string[];
      /**
       * Confirmed Words
       * @default []
       */
      confirmed_words: string[];
      /**
       * Kp Ratings
       * @default {}
       */
      kp_ratings: {
        [key: string]: "again" | "hard" | "good" | "easy" | "skip";
      };
      /** Lesson Id */
      lesson_id: string;
      /**
       * Word Ratings
       * @default {}
       */
      word_ratings: {
        [key: string]: "again" | "hard" | "good" | "easy" | "skip";
      };
    };
    /**
     * MarkLessonReviewedResponse
     * @description Response of POST /api/srs/lesson/{lesson_id}/reviewed.
     */
    MarkLessonReviewedResponse: {
      /** Ok */
      ok: boolean;
    };
    /** PipelineRegenerateRequest */
    PipelineRegenerateRequest: {
      /** Day */
      day: number;
      /**
       * Strategy
       * @default WIDER
       * @enum {string}
       */
      strategy: "WIDER" | "DEEPER";
    };
    /** PipelineRetryRequest */
    PipelineRetryRequest: {
      /** Day */
      day: number;
    };
    /**
     * PlanCommitResponse
     * @description Response of POST /api/curriculum/{curriculum_id}/plan/commit.
     */
    PlanCommitResponse: {
      /** Days */
      days: number;
      /** Id */
      id: string;
    };
    /** PlanFeedbackRequest */
    PlanFeedbackRequest: {
      /** Day */
      day: number;
      /** Note */
      note: string;
    };
    /**
     * PlanFeedbackResponse
     * @description Response of POST /api/curriculum/{curriculum_id}/plan/feedback.
     */
    PlanFeedbackResponse: {
      /** Feedback */
      feedback: unknown[];
    };
    /**
     * PlanResetResponse
     * @description Response of POST /api/curriculum/{curriculum_id}/plan/reset.
     */
    PlanResetResponse: {
      /** Reply Count Cleared */
      reply_count_cleared: number;
    };
    /**
     * PlanTurnPromptResponse
     * @description Response of POST /api/curriculum/{curriculum_id}/plan/turn/prompt.
     */
    PlanTurnPromptResponse: {
      /** System Prompt */
      system_prompt: string;
      /** User Prompt */
      user_prompt: string;
    };
    /** PlanTurnRequest */
    PlanTurnRequest: {
      /**
       * Batch Size
       * @default 5
       */
      batch_size: number;
      /** Message */
      message: string;
      /** Pasted Response */
      pasted_response?: string | null;
    };
    /**
     * PlanTurnResponse
     * @description Response of POST /api/curriculum/{curriculum_id}/plan/turn.
     */
    PlanTurnResponse: {
      /** Proposed */
      proposed?: {
        [key: string]: unknown;
      } | null;
      /** Reply */
      reply: string;
    };
    /** RenderAudioRequest */
    RenderAudioRequest: {
      /** Lesson Id */
      lesson_id: string;
    };
    /**
     * SetGenerationModeResponse
     * @description Response of POST /api/curriculum/{curriculum_id}/generation-mode.
     */
    SetGenerationModeResponse: {
      /** Mode */
      mode: string;
    };
    /** SetStateRequest */
    SetStateRequest: {
      /** State */
      state: string;
    };
    /** StartPlanRequest */
    StartPlanRequest: {
      /**
       * Cefr Level
       * @default A2
       */
      cefr_level: string;
      /** Topic */
      topic: string;
    };
    /**
     * StartPlanResponse
     * @description Response of POST /api/curriculum/plan.
     */
    StartPlanResponse: {
      /** Cefr Level */
      cefr_level: string;
      /** Days */
      days: number;
      /** Id */
      id: string;
      /** Language Code */
      language_code: string;
      /** Topic */
      topic: string;
    };
    /**
     * StatusResponse
     * @description Response of endpoints that return only a fixed ``status`` string:
     *     DELETE /api/srs/items/{id}, POST /api/srs/ignored-lemmas,
     *     DELETE /api/srs/ignored-lemmas.
     */
    StatusResponse: {
      /** Status */
      status: string;
    };
    /** SuspendRequest */
    SuspendRequest: {
      /** Direction */
      direction?: string | null;
      /** Suspended */
      suspended: boolean;
    };
    /** TranslateRequest */
    TranslateRequest: {
      /** Language Code */
      language_code: string;
      /** Text */
      text: string;
    };
    /** UpdateItemRequest */
    UpdateItemRequest: {
      /** Text */
      text: string;
      /** Translation */
      translation: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** _UrlBody */
    _UrlBody: {
      /** Url */
      url: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  refresh_media_api_admin_refresh_media_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  trigger_peer_sync_api_anki_peer_sync_post: {
    parameters: {
      query?: {
        dry_run?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_lesson_audio_api_audio_lesson__lesson_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetLessonAudioResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  download_lesson_zip_api_audio_lesson__lesson_id__zip_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  render_audio_api_audio_render_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenderAudioRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_audio_api_audio__audio_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        audio_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_curricula_api_curriculum_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  import_curriculum_plan_api_curriculum_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportPlanRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportCurriculumPlanResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_plan_api_curriculum_plan_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartPlanRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StartPlanResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_curriculum_api_curriculum__curriculum_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_curriculum_api_curriculum__curriculum_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeleteCurriculumResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_day_api_curriculum__curriculum_id__days__day__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
        day: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeleteDayResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_lesson_by_day_api_curriculum__curriculum_id__days__day__lesson_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
        day: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_generation_mode_api_curriculum__curriculum_id__generation_mode_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerationModeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetGenerationModeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pipeline_status_api_curriculum__curriculum_id__pipeline_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pipeline_regenerate_api_curriculum__curriculum_id__pipeline_regenerate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PipelineRegenerateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pipeline_retry_api_curriculum__curriculum_id__pipeline_retry_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PipelineRetryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  plan_commit_api_curriculum__curriculum_id__plan_commit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanCommitResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  plan_feedback_api_curriculum__curriculum_id__plan_feedback_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlanFeedbackRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanFeedbackResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  plan_reset_api_curriculum__curriculum_id__plan_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanResetResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  plan_turn_api_curriculum__curriculum_id__plan_turn_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlanTurnRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanTurnResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  plan_turn_prompt_api_curriculum__curriculum_id__plan_turn_prompt_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlanTurnRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanTurnPromptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_curriculum_progress_api_curriculum__curriculum_id__progress_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_curriculum_source_api_curriculum__curriculum_id__source_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculum_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  languages_api_languages_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  llm_activity_api_llm_activity_get: {
    parameters: {
      query?: {
        since?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  llm_health_api_llm_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  rate_limit_status_api_llm_rate_limit_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  rate_limit_probe_api_llm_rate_limit_probe_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  backfill_translations_api_srs_backfill_translations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  get_due_collocations_api_srs_due_get: {
    parameters: {
      query?: {
        direction?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_ignored_lemma_api_srs_ignored_lemmas_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IgnoreLemmaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_ignored_lemma_api_srs_ignored_lemmas_delete: {
    parameters: {
      query: {
        lemma: string;
        language_code: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_inflection_cloze_api_srs_inflection_clozes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InflectionClozeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_items_api_srs_items_get: {
    parameters: {
      query?: {
        search?: string | null;
        state?: string | null;
        sort?: string;
        order?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_item_api_srs_items_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateItemRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_base_card_api_srs_items_base_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBaseCardRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bulk_delete_items_api_srs_items_bulk_delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkDeleteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_item_api_srs_items__item_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_item_api_srs_items__item_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateItemRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  drill_feedback_api_srs_items__item_id__direction__direction__feedback_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
        direction: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DrillRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  undo_grade_api_srs_items__item_id__direction__direction__undo_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
        direction: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  put_image_from_url_api_srs_items__item_id__image_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["_UrlBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_image_api_srs_items__item_id__image_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_image_candidates_api_srs_items__item_id__image_candidates_get: {
    parameters: {
      query?: {
        q?: string | null;
      };
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  put_image_upload_api_srs_items__item_id__image_upload_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_put_image_upload_api_srs_items__item_id__image_upload_put"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reset_item_api_srs_items__item_id__reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  restore_known_item_api_srs_items__item_id__restore_known_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_item_state_api_srs_items__item_id__state_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetStateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  suspend_item_api_srs_items__item_id__suspend_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SuspendRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  untrack_item_api_srs_items__item_id__untrack_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  commit_pending_grades_api_srs_lesson__lesson_id__commit_pending_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitPendingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_listen_preview_api_srs_lesson__lesson_id__listen_preview_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListenPreviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_lesson_review_queue_api_srs_lesson__lesson_id__review_queue_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mark_lesson_reviewed_api_srs_lesson__lesson_id__reviewed_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarkLessonReviewedResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_lesson_transcript_api_srs_lesson__lesson_id__transcript_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mark_lesson_listened_api_srs_listen_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ListenRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_listens_api_srs_listens_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  import_listens_api_srs_listens_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportListensRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  serve_media_api_srs_media__filename__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filename: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_new_collocations_api_srs_new_get: {
    parameters: {
      query?: {
        limit?: number;
        direction?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_queue_stats_api_srs_queue_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  get_review_queue_api_srs_review_queue_get: {
    parameters: {
      query?: {
        session_start?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_stats_api_srs_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  translate_api_srs_translate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TranslateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  translate_missing_api_srs_translate_missing_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  generate_story_api_story_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateStoryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenerateStoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_story_api_story_import_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportLessonRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_story_prompt_api_story_prompt_get: {
    parameters: {
      query: {
        curriculum_id: string;
        day: number;
        strategy?: "WIDER" | "DEEPER";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetStoryPromptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_lesson_api_story__lesson_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_lesson_source_api_story__lesson_id__source_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
